package l5x

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/joyautomation/nautilus/internal/tagfile"
)

// TagsOptions controls which of an export's tags become a tag file.
type TagsOptions struct {
	// Scope selects the tags to emit: "" for controller-scoped tags only
	// (the default, and what a nautilus project normally binds), a
	// program name for that program's tags, or "*" for every scope. A
	// program-scoped tag is named "<Program>_<Tag>", since a nautilus tag
	// name is a flat identifier and two programs may each have a Sts.
	Scope string
	// Skip holds path.Match globs for tags to leave out, matched against
	// the emitted name. Same escape hatch as `nautilus eip import
	// --tags-skip`: a tag the project declares by hand is skipped here so
	// the two never collide.
	Skip []string
	// KnownTypes, when non-nil, is the set of UDT names the companion
	// logix_types.st actually declares. A tag whose type is not in it is
	// emitted untyped rather than pointing at a type that does not exist.
	KnownTypes map[string]bool
	// Constants includes Logix "Constant" tags. Off by default: they are
	// literals the controller will not let anything write, so binding one
	// as a runtime tag is usually a mistake.
	Constants bool
}

// Tags converts an export's tags to nautilus tag declarations.
//
// The descriptions are the point. Logix keeps tag documentation in the
// offline project file, so a live CIP browse cannot see it and
// `nautilus eip import` has to leave desc: empty (eip/codegen/tags.go).
// The same tags read from an L5X arrive documented.
//
// Role is "input" for every tag. Direction is a property of the nautilus
// project — which tags it drives — not of the controller, and an L5X says
// nothing about it. Flipping one to output is a one-word edit in the
// project that knows.
func Tags(f *File, opts TagsOptions) ([]tagfile.Tag, error) {
	if f == nil || f.Controller == nil {
		return nil, fmt.Errorf("l5x: no controller to read tags from")
	}
	var out []tagfile.Tag
	add := func(t *Tag, scope string) {
		if t.Name == "" {
			return
		}
		if t.Constant && !opts.Constants {
			return
		}
		name := ident(t.Name)
		if scope != "" {
			name = ident(scope) + "_" + name
		}
		for _, p := range opts.Skip {
			if ok, err := path.Match(p, name); err == nil && ok {
				return
			}
		}
		tag := tagfile.Tag{Name: name, Role: "input", Desc: t.Description}
		// An array's shape comes from the driver that delivers it; a tag
		// file has no syntax for one, so it stays untyped and unseeded.
		if t.Dimensions == "" {
			if _, elem := elementary[strings.ToUpper(t.DataType)]; !elem && t.DataType != "" {
				typeName := ident(t.DataType)
				if opts.KnownTypes == nil || opts.KnownTypes[typeName] {
					tag.Type = typeName
					tag.Init = structInit(t.Value)
				}
			} else if elem {
				tag.Init = scalarInit(t.Value)
			}
		}
		out = append(out, tag)
	}

	switch opts.Scope {
	case "":
		for _, t := range f.Controller.Tags {
			add(t, "")
		}
	case "*":
		for _, t := range f.Controller.Tags {
			add(t, "")
		}
		for _, p := range f.Controller.Programs {
			for _, t := range p.Tags {
				add(t, p.Name)
			}
		}
	default:
		found := false
		for _, p := range f.Controller.Programs {
			if p.Name != opts.Scope {
				continue
			}
			found = true
			for _, t := range p.Tags {
				add(t, p.Name)
			}
		}
		if !found {
			return nil, fmt.Errorf("l5x: no program named %q (scope is a program name, \"\" for controller tags, or \"*\" for all)", opts.Scope)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

// TagsYAML renders an export's tags as a nautilus tag file — the bare YAML
// list a project composes through `tag-files:`.
func TagsYAML(f *File, opts TagsOptions) ([]byte, error) {
	tags, err := Tags(f, opts)
	if err != nil {
		return nil, err
	}
	src := f.TargetName
	if src == "" && f.Controller != nil {
		src = f.Controller.Name
	}
	header := []string{
		fmt.Sprintf("Generated by `nautilus logix import` from the %s L5X export.", src),
		"Do not edit — re-run the import.",
		"",
		"Compose it into a project with:  tag-files: [tags/logix.yaml]",
		"",
		"desc: comes from the offline project's own tag documentation, which",
		"a live CIP browse cannot see. role: is input for every tag — an L5X",
		"says which tags exist, not which ones this project drives.",
	}
	if len(opts.Skip) > 0 {
		header = append(header, "",
			"Not generated (declared by hand): "+strings.Join(opts.Skip, ", "))
	}
	return tagfile.Render(header, tags)
}

// scalarInit returns a decoded scalar suitable as a tag's init, or nil.
func scalarInit(v any) any {
	switch v.(type) {
	case bool, int64, float64, string:
		return v
	}
	return nil
}

// structInit returns a struct tag's per-member seed — the flow mapping
// tagfile renders as `init: { PRE: 6, ACC: 0 }` — or nil when the export
// carries no decorated value. Array members are dropped: a tag file's
// init mapping has no syntax for a list.
//
// Keys go through the same identifier mapping the type declaration used,
// so a seed lands on the field it names. A UDT member called "retain"
// declares as retain_ (an IEC keyword), and an init keyed "retain" would
// silently seed nothing.
func structInit(v any) any {
	m, ok := v.(map[string]any)
	if !ok || len(m) == 0 {
		return nil
	}
	out := map[string]any{}
	for name, mv := range m {
		k := ident(name)
		switch x := mv.(type) {
		case map[string]any:
			if nested := structInit(x); nested != nil {
				out[k] = nested
			}
		case bool, int64, float64, string:
			out[k] = mv
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}
