#!/usr/bin/env python3
"""Generate the plant's tags, replay manifest and plant.st from a recorded
cluster: the monitoring project's manifests (which devices, which tags), its
recording (history.json.gz, the SNMP walks). Re-run it; do not edit what it
writes.

  python3 gen.py --dataset <dir> --monitor <dir> [--at 2026-09-28T18:00Z]

  --dataset   history.json.gz + snmp/<host>.snmpwalk (also linked as ./data,
              which the replay driver reads at run time; not committed)
  --monitor   the monitoring project: snmp_manifest.yaml, redfish_manifest.yaml
  --at        the recorded moment the device tags start at, and hold when
              the recording is absent
  --naut      the naut binary (default: naut on PATH)
  --walk      each switch's walk under <dataset>/snmp (default {tag}.snmpwalk)

Per recorded device tag X (SW1_Port25, NODE1_Fan3, ...):

  Rec_X   input   the recording, delivered by the replay driver
  Sim_X   state   the fault inputs (switch ports and switches, so far)
  X       state   what the device reports: identity from the walk read
                  through the manifest (`naut snmp read`), the recorded
                  members bent by the faults (plant.st); the stand-ins serve
                  it through the monitoring project's own manifest
"""
import argparse, datetime, gzip, json, os, re, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))

ap = argparse.ArgumentParser()
ap.add_argument("--dataset", required=True)
ap.add_argument("--monitor", required=True)
ap.add_argument("--at", default="2026-09-28T18:00Z")
ap.add_argument("--naut", default="naut")
ap.add_argument("--walk", default="{tag}.snmpwalk", help="walk file name under <dataset>/snmp, {tag} = sw1")
args = ap.parse_args()


def manifest_tags(path):
    """(name, type, source) in manifest order: the monitoring project's device list."""
    out = []
    for line in open(path):
        m = re.match(r"- name: (\S+)", line)
        if m:
            out.append([m.group(1), None, None])
        m = re.match(r"  (type|source): (\S+)", line)
        if m and out:
            out[-1][1 if m.group(1) == "type" else 2] = m.group(2)
    return out


snmp_tags = manifest_tags(os.path.join(args.monitor, "snmp_manifest.yaml"))
redfish_tags = manifest_tags(os.path.join(args.monitor, "redfish_manifest.yaml"))
switches = [n for n, t, _ in snmp_tags if t == "Switch"]
ports = [n for n, t, _ in snmp_tags if t == "SwitchPort"]
types = {n: t for n, t, _ in snmp_tags + redfish_tags}

h = json.load(gzip.open(os.path.join(args.dataset, "history.json.gz")))
recorded = sorted({k.split(".")[0] for k in h["series"]} & set(types), key=list(types).index)
at = datetime.datetime.strptime(args.at, "%Y-%m-%dT%H:%MZ").replace(tzinfo=datetime.timezone.utc).timestamp()
idx = min(max(0, round((at - h["t0"]) / h["step"])), h["n"] - 1)
stamp = datetime.datetime.fromtimestamp(h["t0"] + idx * h["step"], datetime.timezone.utc).strftime("%Y-%m-%dT%H:%MZ")

# Identity: each switch's walk read forwards through the monitor's manifest.
walks = {}
for sw in switches:
    walk = os.path.join(args.dataset, "snmp", args.walk.format(tag=sw.lower()))
    out = subprocess.run([args.naut, "snmp", "read", "--walk", walk, "--source", sw,
                          "--manifest", os.path.join(args.monitor, "snmp_manifest.yaml")],
                         check=True, capture_output=True, text=True).stdout
    walks.update(json.loads(out))


# This project is public: no hostnames, no serials (docs: sourcing). Models
# and port names are the commodity hardware's own and stay.
SCRUB = {"Switch": lambda n: {"Name": n.lower(), "Serial": f"SIM-{n}"}}


def snapshot(name):
    """The device at --at: identity from the walk, recorded members from history."""
    v = dict(walks[name])
    v.update(SCRUB.get(types[name], lambda n: {})(name))
    for k in list(v):
        s = h["series"].get(f"{name}.{k}")
        if s and s[idx] is not None:
            v[k] = bool(s[idx]) if f"{name}.{k}" in h["bool"] else s[idx]
    return v


def lit(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, float) and v == int(v) and abs(v) < 1e15:
        return f"{v:.1f}"
    return repr(v)


def init(d):
    return "{ " + ", ".join(f"{k}: {lit(v)}" for k, v in d.items()) + " }"


head = "# Generated by gen.py from the recorded cluster. Re-run it; do not edit.\n"

# replay_manifest.yaml: every recorded tag whose contract type exists.
rm = [head, "# The replay driver's recording: ./data is a link to the dataset (not committed).",
      "history: data/history.json.gz", "tags:"]
for n in recorded:
    rm.append(f"  - {{ name: Rec_{n}, type: {types[n]}, series: {n} }}")
open(os.path.join(HERE, "replay_manifest.yaml"), "w").write("\n".join(rm) + "\n")

rec = [head + "# The recording, one input per recorded device tag (driver: replay)."]
for n in recorded:
    rec.append(f"- {{ name: Rec_{n}, role: input, type: {types[n]}, init: {{}}, desc: \"{n} as recorded\" }}")
open(os.path.join(HERE, "tags", "recorded.yaml"), "w").write("\n".join(rec) + "\n")

sw = [head + f"# The switches as the plant reports them, starting at the recording's {stamp}."]
for n in switches + ports:
    typ, sim = ("Switch", "SimSwitch") if n in switches else ("SwitchPort", "SimPort")
    sw.append(f"- {{ name: Sim_{n}, role: state, type: {sim}, desc: \"{n} fault inputs (SIMULATION)\" }}")
    sw.append(f"- {{ name: {n}, role: state, type: {typ}, init: {init(snapshot(n))}, desc: \"{n} as the plant reports it\" }}")
open(os.path.join(HERE, "tags", "switches.yaml"), "w").write("\n".join(sw) + "\n")

ext, fbs, body = [], [], []
for n in switches + ports:
    typ, sim = ("Switch", "SimSwitch") if n in switches else ("SwitchPort", "SimPort")
    r = f" Rec_{n} : {typ};" if n in recorded else ""
    ext.append(f"  Sim_{n} : {sim}; {n} : {typ};{r}")
for s in switches:
    body.append(f"  {s}.Online := NOT Sim_{s}.Dark;")
    body.append(f"  {s}.PortsUp := 0;")
    for p in [p for p in ports if p.startswith(s + "_")]:
        fbs.append(f"  {p}_M : PortPlant;")
        body.append(f"  {p}_M(Rec := Rec_{p}, F := Sim_{p}, Dark := Sim_{s}.Dark, Live := Live, P := {p});")
        body.append(f"  IF {p}.OperUp THEN {s}.PortsUp := {s}.PortsUp + 1; END_IF;")
nl = "\n"
st = f"""(* plant.st: generated by gen.py; the logic is lib/switch.st. Do not edit.
   Every device tag is its recorded baseline, Rec_..., bent by its fault
   inputs, Sim_...: write Sim_SW1_Port25.Down := TRUE and SW1_Port25 loses
   link, on the wire of the stand-in that serves it. *)
PROGRAM Plant
VAR_EXTERNAL
  (* the replay clock: the HMI steers the outputs, the driver reports At *)
  Replay_At : DINT; Replay_Speed : REAL; Replay_Pause : BOOL; Replay_SeekS : DINT;
{nl.join(ext)}
END_VAR
VAR
  Live : BOOL;
{nl.join(fbs)}
END_VAR
  Live := Replay_At > 0;
{nl.join(body)}
END_PROGRAM
"""
open(os.path.join(HERE, "plant.st"), "w").write(st)

link = os.path.join(HERE, "data")
if not os.path.lexists(link):
    os.symlink(os.path.abspath(args.dataset), link)
print(f"{len(switches)} switches, {len(ports)} ports, {len(recorded)} recorded tags; snapshot at {stamp}")
