// manifest.go is the committed description of what a project scrapes over
// Prometheus: the sources (one `/metrics` URL each) and the struct-tag
// bindings onto their series. Generated by `naut prometheus import`;
// validated offline in New so `naut check` and `build` pass with no exporter
// in sight.
//
// The YAML shapes carry NO yaml struct tags of their own — modbus/manifest.go's
// convention exactly: the on-disk keys are the lowercased Go field names
// ("bearerenv", "staleafter"), decoded with KnownFields(true) semantics so a
// typo is an error rather than a silently dropped binding. Duration fields
// are the one wrinkle (time.Duration has no YAML face of its own) and decode
// through the same shadow-struct trick. The one exception is hw.Binding,
// embedded inline in Binding below: it is hw/'s own vocabulary and keeps
// hw/'s own key spellings (const, map, eq, scale, offset, rate, width,
// scan-class, derived) — see docs/design/it-drivers.md §6.1.
package prom

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"reflect"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/joyautomation/nautilus/hw"
	"github.com/joyautomation/nautilus/lang/ir"
)

// Manifest is one project's Prometheus surface: the sources it scrapes, the
// struct tags bound onto them, and (shape parity with the other two
// drivers, currently always empty — scraping is one-way) opt-in writes.
type Manifest struct {
	Sources []Source
	Tags    []Tag
	Writes  []hw.WriteDecl
}

// Source is one `/metrics` endpoint.
type Source struct {
	// ID names the source: Tag.Source refers to it, and the /api/drivers
	// device row and the synthesized "<id>__Online"/"<id>__LastPollMs"
	// companions carry it.
	ID string
	// URL is the full scrape URL ("http://host:9100/metrics").
	URL string
	// Timeout bounds the GET; 0 means the driver default (5s).
	Timeout time.Duration
	// Interval is this source's default-class poll period; 0 takes the
	// driver's WithScanRate (15s default — node_exporter's own rate,
	// docs/design/it-drivers.md §3.3).
	Interval time.Duration
	// StaleAfter: a source whose last complete scrape is older than this
	// reports Stale even while "connected" (default 3×Interval).
	StaleAfter time.Duration
	// Enable optionally names a BOOL tag; false parks the source.
	Enable string
	// BearerEnv/BearerFile name a bearer token for an exporter behind a
	// proxy that wants one — "*-env: VAR" or "*-file: path", never both
	// (Validate). node_exporter itself needs neither.
	BearerEnv  string
	BearerFile string
	// BasicEnv/BasicFile name a "user:password" credential for HTTP basic
	// auth, the same both-or-neither rule.
	BasicEnv  string
	BasicFile string
	// InsecureSkipVerify accepts a self-signed cert on an https:// URL — an
	// exporter behind a reverse proxy with an internal CA, most commonly.
	InsecureSkipVerify bool
}

// Tag is one struct tag: a contract type (hw.TypeByName), the source it
// scrapes, and the binding vocabulary per member. A member absent from the
// map is never updated and stays at zero-of-field (hw.TagDecl's rule).
type Tag struct {
	Name    string
	Type    string
	Source  string
	Members map[string]Binding
}

// Binding is a Prometheus member binding: hw's shared vocabulary
// (const/map/eq/scale/offset/rate/width/scan-class/derived), plus the
// locator this protocol adds — docs/design/it-drivers.md §3.3, §6.3.
//
// Exactly one of three shapes applies, mutually exclusive (Validate):
//
//   - hw.Binding.Const or .Derived — no locator at all, hw's own rules.
//   - Metric (+ optional Labels/Agg/Label/Rate/Width) — one bound series.
//   - Expr (+ From) — arithmetic over named selectors, §6.3.
type Binding struct {
	hw.Binding `yaml:",inline"`

	// Metric is the series name; Labels narrows it to an exact match on the
	// given labels (other labels on the series are free — a chip/sensor
	// pair identifies one node_hwmon_temp_celsius row without caring what
	// else the exporter attaches).
	Metric string
	Labels map[string]string
	// Agg combines several matching series into one number: sum, max, min,
	// avg or count. Required when Labels alone does not narrow the match to
	// exactly one series; an error otherwise (ambiguous binding).
	Agg string
	// Label takes the NAMED LABEL's value as a STRING member instead of the
	// series' sample value — Server.Model from node_uname_info{nodename},
	// docs/design/it-drivers.md §3.3's "a label as a STRING value".
	Label string

	// Expr is arithmetic over the named selectors in From (hw.ParseExpr —
	// four operators, parentheses, named selectors); From's keys are the
	// expression's variables, resolved against the same scrape. The
	// built-in name "__now" is always available (the poll's wall clock in
	// seconds) with no entry in From.
	Expr string
	From map[string]Selector
}

// Selector is one named input to an Expr: the same metric+labels+agg
// locator as a plain Binding, plus its own independent Rate — CpuPct's
// `idle` selector rates node_cpu_seconds_total while `cpus` (a count of how
// many CPUs exist) does not.
type Selector struct {
	Metric string
	Labels map[string]string
	Agg    string
	Rate   bool
	Label  string
}

// builtinNow is the identifier every Expr may use with no From entry: the
// poll's wall clock, in seconds — UptimeS's "__now - boot" (§3.3's node
// profile; the alternative, computing uptime from the boot timestamp inside
// the manifest, would need a second built-in for "now" anyway).
const builtinNow = "__now"

// ── YAML ─────────────────────────────────────────────────────────────────

// LoadManifest decodes a prometheus_manifest.yaml. It does not validate —
// call Validate (New does) for the cross-references and credential rules.
func LoadManifest(r io.Reader) (Manifest, error) {
	var m Manifest
	dec := yaml.NewDecoder(r)
	dec.KnownFields(true)
	if err := dec.Decode(&m); err != nil {
		if errors.Is(err, io.EOF) {
			return Manifest{}, fmt.Errorf("prom: manifest is empty")
		}
		return Manifest{}, fmt.Errorf("prom: manifest: %w", err)
	}
	return m, nil
}

// ParseManifest decodes a manifest from bytes.
func ParseManifest(data []byte) (Manifest, error) {
	return LoadManifest(bytes.NewReader(data))
}

// duration parses "5s"/"2.5s" yaml scalars — modbus.Manifest's wrinkle,
// kept package-private because the public structs carry plain
// time.Duration.
type duration time.Duration

func (d *duration) UnmarshalYAML(node *yaml.Node) error {
	v, err := time.ParseDuration(node.Value)
	if err != nil {
		return fmt.Errorf("bad duration %q (want e.g. 5s, 2.5s)", node.Value)
	}
	*d = duration(v)
	return nil
}

func (d duration) MarshalYAML() (any, error) { return time.Duration(d).String(), nil }

// sourceYAML mirrors Source with parseable duration fields — field names
// must stay identical to Source's, because the lowercased names ARE the
// on-disk keys and the copy below is by name.
type sourceYAML struct {
	ID                 string
	URL                string
	Timeout            duration
	Interval           duration
	StaleAfter         duration
	Enable             string
	BearerEnv          string
	BearerFile         string
	BasicEnv           string
	BasicFile          string
	InsecureSkipVerify bool
}

func (s *Source) UnmarshalYAML(node *yaml.Node) error {
	var r sourceYAML
	if err := strictDecode(node, &r); err != nil {
		return err
	}
	*s = Source{
		ID: r.ID, URL: r.URL, Timeout: time.Duration(r.Timeout),
		Interval: time.Duration(r.Interval), StaleAfter: time.Duration(r.StaleAfter),
		Enable: r.Enable, BearerEnv: r.BearerEnv, BearerFile: r.BearerFile,
		BasicEnv: r.BasicEnv, BasicFile: r.BasicFile, InsecureSkipVerify: r.InsecureSkipVerify,
	}
	return nil
}

func (s Source) MarshalYAML() (any, error) {
	return sourceYAML{
		ID: s.ID, URL: s.URL, Timeout: duration(s.Timeout),
		Interval: duration(s.Interval), StaleAfter: duration(s.StaleAfter),
		Enable: s.Enable, BearerEnv: s.BearerEnv, BearerFile: s.BearerFile,
		BasicEnv: s.BasicEnv, BasicFile: s.BasicFile, InsecureSkipVerify: s.InsecureSkipVerify,
	}, nil
}

func (t *Tag) UnmarshalYAML(node *yaml.Node) error {
	type tagYAML struct {
		Name    string
		Type    string
		Source  string
		Members map[string]Binding
	}
	var r tagYAML
	if err := strictDecode(node, &r); err != nil {
		return err
	}
	*t = Tag(r)
	return nil
}

// strictDecode decodes node into v and rejects any key the struct does not
// declare (by its lowercased field name) — modbus.strictDecode's trick,
// because KnownFields does not survive into a custom UnmarshalYAML.
func strictDecode(node *yaml.Node, v any) error {
	if err := node.Decode(v); err != nil {
		return err
	}
	if node.Kind != yaml.MappingNode {
		return nil
	}
	t := reflect.TypeOf(v).Elem()
	known := make(map[string]bool, t.NumField())
	names := make([]string, 0, t.NumField())
	for i := range t.NumField() {
		name := strings.ToLower(t.Field(i).Name)
		known[name] = true
		names = append(names, name)
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if k := node.Content[i]; !known[k.Value] {
			return fmt.Errorf("line %d: unknown key %q%s", k.Line, k.Value, didYouMean(k.Value, names))
		}
	}
	return nil
}

func didYouMean(got string, names []string) string {
	for _, n := range names {
		if n == got {
			return ""
		}
	}
	// A cheap, honest hint: only suggest an exact substring relationship —
	// no fuzzy distance, so it never suggests something misleading.
	for _, n := range names {
		if strings.Contains(n, got) || strings.Contains(got, n) {
			return fmt.Sprintf(" (did you mean %q?)", n)
		}
	}
	return ""
}

// ── validation ───────────────────────────────────────────────────────────

// Validate checks the manifest offline: every reference resolves, every
// binding is legal for its member, credentials follow the *-env/*-file
// rule. It is the whole of what `naut check` needs — no exporter is ever
// contacted. Findings are reported together (errors.Join).
func (m Manifest) Validate() error {
	var errs []error

	byID := make(map[string]Source, len(m.Sources))
	ids := make([]string, 0, len(m.Sources))
	for _, s := range m.Sources {
		if s.ID == "" {
			errs = append(errs, fmt.Errorf("source with url %q: missing id", s.URL))
			continue
		}
		if _, dup := byID[s.ID]; dup {
			errs = append(errs, fmt.Errorf("duplicate source id %q", s.ID))
			continue
		}
		byID[s.ID] = s
		ids = append(ids, s.ID)
		if s.URL == "" {
			errs = append(errs, fmt.Errorf("source %s: missing url", s.ID))
		}
		if s.Timeout < 0 || s.Interval < 0 || s.StaleAfter < 0 {
			errs = append(errs, fmt.Errorf("source %s: negative duration", s.ID))
		}
		if s.BearerEnv != "" && s.BearerFile != "" {
			errs = append(errs, fmt.Errorf("source %s: bearerenv and bearerfile are both set — a secret has exactly one home", s.ID))
		}
		if s.BasicEnv != "" && s.BasicFile != "" {
			errs = append(errs, fmt.Errorf("source %s: basicenv and basicfile are both set — a secret has exactly one home", s.ID))
		}
	}

	seen := make(map[string]bool, len(m.Tags))
	for _, tg := range m.Tags {
		if tg.Name == "" {
			errs = append(errs, fmt.Errorf("tag on source %q: missing name", tg.Source))
			continue
		}
		if seen[tg.Name] {
			errs = append(errs, fmt.Errorf("duplicate tag name %q", tg.Name))
			continue
		}
		seen[tg.Name] = true
		if strings.Contains(tg.Name, ".") {
			errs = append(errs, fmt.Errorf("tag %q: a tag name cannot contain '.'", tg.Name))
		}
		if _, ok := byID[tg.Source]; !ok {
			errs = append(errs, fmt.Errorf("tag %s: unknown source %q%s", tg.Name, tg.Source, didYouMean(tg.Source, ids)))
		}
		fields, ok := hw.TypeByName(tg.Type)
		if !ok {
			errs = append(errs, fmt.Errorf("tag %s: unknown type %q (the IT-hardware set is %s)", tg.Name, tg.Type, hw.TypeNames()))
			continue
		}
		for member, b := range tg.Members {
			_, f, ok := hw.FieldOf(fields.Name, member)
			if !ok {
				errs = append(errs, fmt.Errorf("tag %s: member %s: %s has no such member", tg.Name, member, tg.Type))
				continue
			}
			if err := b.validateLocator(f); err != nil {
				errs = append(errs, fmt.Errorf("tag %s: member %s: %w", tg.Name, member, err))
			}
		}
	}

	for _, w := range m.Writes {
		if w.Name == "" {
			errs = append(errs, fmt.Errorf("a write has no name"))
			continue
		}
		if _, ok := seen[w.Tag]; !ok {
			errs = append(errs, fmt.Errorf("write %s: targets unknown tag %q", w.Name, w.Tag))
		}
	}

	if len(errs) == 0 {
		return nil
	}
	return errors.Join(errs...)
}

// validateLocator checks the shape ABOVE hw.Binding — that at most one of
// const/derived/metric/expr is given, and that whichever is given resolves
// against the member — plus hw.Binding.Validate for the shared keys.
func (b Binding) validateLocator(f hw.Field) error {
	locators := 0
	if b.Metric != "" {
		locators++
	}
	if b.Expr != "" {
		locators++
	}
	if b.Binding.Const != nil || b.Binding.Derived != "" {
		locators++
		if b.Metric != "" || b.Expr != "" || b.Label != "" || len(b.Labels) > 0 || b.Agg != "" || len(b.From) > 0 {
			return fmt.Errorf("const/derived take no metric/expr/labels/agg/label/from")
		}
	}
	if locators > 1 {
		return fmt.Errorf("exactly one of const, derived, metric or expr")
	}
	if locators == 0 {
		return fmt.Errorf("needs one of const, derived, metric or expr")
	}
	if b.Metric != "" {
		if b.Expr != "" || len(b.From) > 0 {
			return fmt.Errorf("metric: and expr:/from: are alternatives")
		}
		if b.Label != "" {
			if f.Kind != ir.TypeString {
				return fmt.Errorf("label: makes a STRING, but the member is %s", f.Kind)
			}
			if b.Agg != "" || b.Rate {
				return fmt.Errorf("label: takes no agg/rate — a label is a string, not a series to aggregate or rate")
			}
		}
		if b.Agg != "" {
			if err := validateAgg(b.Agg); err != nil {
				return err
			}
		}
	}
	if b.Expr != "" {
		expr, err := hw.ParseExpr(b.Expr)
		if err != nil {
			return err
		}
		for _, v := range expr.Vars() {
			if v == builtinNow {
				continue
			}
			sel, ok := b.From[v]
			if !ok {
				return fmt.Errorf("expr %q names %q, which has no entry in from:", b.Expr, v)
			}
			if sel.Metric == "" {
				return fmt.Errorf("from: %s: missing metric", v)
			}
			if sel.Agg != "" {
				if err := validateAgg(sel.Agg); err != nil {
					return fmt.Errorf("from: %s: %w", v, err)
				}
			}
		}
		for name := range b.From {
			found := false
			for _, v := range expr.Vars() {
				if v == name {
					found = true
					break
				}
			}
			if !found {
				return fmt.Errorf("from: %s: not used by expr %q", name, b.Expr)
			}
		}
	}
	return b.Binding.Validate(f)
}

func validateAgg(agg string) error {
	switch agg {
	case "sum", "max", "min", "avg", "count":
		return nil
	}
	return fmt.Errorf("agg: %q (want sum, max, min, avg or count)", agg)
}
