package codegen

// The importer already knows every tag the manifest implies — the bindings
// and the driver-synthesized companions (__Online, __LastBirthMs, __Rebirth)
// — so the tag file is derivable rather than transcribed. It is rendered
// through the SHARED internal/tagfile.Render, the same helper
// `nautilus eip import` and `nautilus tags import-csv` use, so sorting,
// duplicate rejection and float formatting cannot drift between generators.
//
// Output is a tag FILE (a bare YAML list) rather than a manifest section, so
// it composes through tag-files: and stays a separate reviewable artifact:
// regenerating it never touches the file a person edits.

import (
	"fmt"
	"path"
	"strings"

	"github.com/joyautomation/nautilus/internal/tagfile"
	"github.com/joyautomation/nautilus/sparkplug/host"
)

// TagsYAML renders the manifest's tags as a nautilus tag file.
//
// It is a PURE function of a committed manifest — no broker needed — which is
// what makes `nautilus sparkplug tags <manifest>` work in CI and during
// review, after the import that produced the manifest has long since run.
//
// skip holds path.Match globs for tags to LEAVE OUT. A tag may be declared
// once, so a project that needs to say something the import cannot know —
// most often an `init:` on an input, so the logic runs before the first birth
// instead of faulting — declares that tag by hand and skips it here.
//
// A skip pattern that matches NOTHING is an error, not a warning: it is
// almost always a stale exclusion left behind after a metric was renamed at
// the site, which silently puts the tag back into the generated file, where
// it collides with the hand-written declaration it was meant to make room
// for. (eip's fail-loud rule, tightened from "no pattern matched anything" to
// "every pattern matched something" — with 60 sites, one dead pattern out of
// twenty is exactly the case that hides.)
func TagsYAML(m host.Manifest, skip []string) ([]byte, error) {
	for _, p := range skip {
		if _, err := path.Match(p, ""); err != nil {
			return nil, fmt.Errorf("codegen: bad skip pattern %q: %w", p, err)
		}
	}

	byName := make(map[string]host.Binding, len(m.Tags))
	for _, b := range m.Tags {
		byName[b.Name] = b
	}

	specs := m.TagSpecs()
	hit := make(map[string]int, len(skip))
	out := make([]tagfile.Tag, 0, len(specs))
	for _, s := range specs {
		if p, ok := matchAny(s.Name, skip); ok {
			hit[p]++
			continue
		}
		out = append(out, tagfile.Tag{
			Name: s.Name,
			Role: s.Role,
			Type: s.Type,
			Init: typedInit(s.Init, byName[s.Name].Type),
		})
	}
	for _, p := range skip {
		if hit[p] == 0 {
			return nil, fmt.Errorf("codegen: skip pattern %q matches no tag — "+
				"a stale exclusion would silently regenerate a tag you declare by hand", p)
		}
	}
	header := []string{
		"Generated by `nautilus sparkplug import` from the group's birth",
		"certificates. Do not edit — re-run the import, or",
		"`nautilus sparkplug tags sparkplug_manifest.yaml` to re-derive this file",
		"from the committed manifest alone.",
		"",
		fmt.Sprintf("Group %s · %d node(s) · %d bound metric(s).",
			groupName(m), len(m.Nodes), len(m.Tags)),
		"",
		"Compose it into a project with:  tag-files: [tags/sparkplug.yaml]",
		"",
		"__Online / __LastBirthMs / __Rebirth are synthesized by the driver, not",
		"metrics: a site's values survive its death (Sparkplug's last value IS the",
		"value), so quality rides on these companions. Interlock on __Online.",
	}
	if len(skip) > 0 {
		header = append(header, "",
			"Not generated (declared by hand in the project): "+strings.Join(skip, ", "))
	}
	return tagfile.Render(header, out)
}

// typedInit reconciles an init value with the Sparkplug datatype its binding
// declares. A hand-written (or round-tripped) `init: 0` on a Double binding
// decodes as an int, and an int init renders as "0" — which seeds a DINT tag
// where the driver will deliver a REAL. The manifest's declared type is the
// authority, so the literal follows it.
func typedInit(v any, sparkplugType string) any {
	if v == nil {
		return nil
	}
	switch sparkplugType {
	case "Float", "Double":
		switch n := v.(type) {
		case int:
			return float64(n)
		case int64:
			return float64(n)
		}
	case "Int8", "Int16", "Int32", "Int64",
		"UInt8", "UInt16", "UInt32", "UInt64", "DateTime":
		if f, ok := v.(float64); ok && f == float64(int64(f)) {
			return int64(f)
		}
	}
	return v
}

// groupName is the manifest's group, or a placeholder for a group-less
// manifest (one that consumes every group on the broker).
func groupName(m host.Manifest) string {
	if m.Group == "" {
		return "(all)"
	}
	return m.Group
}

// matchAny reports the first pattern that matches name.
func matchAny(name string, pats []string) (string, bool) {
	for _, p := range pats {
		if ok, err := path.Match(p, name); err == nil && ok {
			return p, true
		}
	}
	return "", false
}
