// render.go writes the generated files by hand rather than yaml.Marshal:
// block-style sources and tags, one flow map per member binding in the
// UDT's own member order — the shape brief §6.1 shows, compact enough to
// review and stable enough to diff. The round trip through
// redfish.ParseManifest is pinned by the tests.
package codegen

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/joyautomation/nautilus/hw"
	"github.com/joyautomation/nautilus/internal/tagfile"
	"github.com/joyautomation/nautilus/redfish"
)

// ManifestYAML renders a manifest. command is the generating invocation
// (without the --host/--mockup flags, which differ between a live import
// and an import of its recording while the bytes must not).
func ManifestYAML(m redfish.Manifest, command string) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `%s` from the BMC's Redfish tree.\n", command)
	b.WriteString("# Do not edit the tags: re-run the import. Commands (writes:) are never\n")
	b.WriteString("# generated — add one by hand, in a reviewed diff (docs/design/it-drivers.md §7).\n")
	b.WriteString("# Validated offline: `naut check` needs no BMC and no password.\n")

	b.WriteString("sources:\n")
	for _, s := range m.Sources {
		fmt.Fprintf(&b, "  - id: %s\n", s.ID)
		fmt.Fprintf(&b, "    host: %s\n", yamlStr(s.Host))
		kv := func(k, v string) {
			if v != "" {
				fmt.Fprintf(&b, "    %s: %s\n", k, yamlStr(v))
			}
		}
		kv("user", s.User)
		kv("password-env", s.PasswordEnv)
		kv("password-file", s.PasswordFile)
		kv("auth", s.Auth)
		if s.TLS.Insecure || s.TLS.CAFile != "" {
			b.WriteString("    tls:\n")
			if s.TLS.Insecure {
				b.WriteString("      insecure: true\n")
			}
			if s.TLS.CAFile != "" {
				fmt.Fprintf(&b, "      ca-file: %s\n", yamlStr(s.TLS.CAFile))
			}
		}
		dur := func(k string, d time.Duration) {
			if d != 0 {
				fmt.Fprintf(&b, "    %s: %s\n", k, d)
			}
		}
		dur("timeout", s.Timeout)
		if s.Retries != 0 {
			fmt.Fprintf(&b, "    retries: %d\n", s.Retries)
		}
		dur("interval", s.Interval)
		dur("stale-after", s.StaleAfter)
		kv("enable", s.Enable)
	}

	b.WriteString("tags:\n")
	for _, t := range m.Tags {
		fmt.Fprintf(&b, "  - name: %s\n", t.Name)
		fmt.Fprintf(&b, "    type: %s\n", t.Type)
		fmt.Fprintf(&b, "    source: %s\n", t.Source)
		if t.Desc != "" {
			fmt.Fprintf(&b, "    desc: %s\n", quote(t.Desc))
		}
		if t.Resource != "" {
			fmt.Fprintf(&b, "    resource: %s\n", yamlStr(t.Resource))
		}
		b.WriteString("    members:\n")
		for _, name := range memberOrder(t) {
			fmt.Fprintf(&b, "      %s: %s\n", name, bindingFlow(t.Members[name]))
		}
	}

	if len(m.Writes) > 0 {
		b.WriteString("writes:\n")
		for _, w := range m.Writes {
			fmt.Fprintf(&b, "  - name: %s\n", w.Name)
			fmt.Fprintf(&b, "    tag: %s\n", w.Tag)
			if w.Member != "" {
				fmt.Fprintf(&b, "    member: %s\n", w.Member)
			}
			fmt.Fprintf(&b, "    target: %s\n", yamlStr(w.Target))
		}
	}
	return []byte(b.String())
}

// memberOrder is the UDT's field order (the order a reader of hw_types.st
// expects), then anything unknown alphabetically (Validate reports those).
func memberOrder(t redfish.Tag) []string {
	var out []string
	seen := map[string]bool{}
	if ty, ok := hw.TypeByName(t.Type); ok {
		for _, f := range ty.Fields {
			if _, ok := t.Members[f.Name]; ok {
				out = append(out, f.Name)
				seen[f.Name] = true
			}
		}
	}
	var rest []string
	for k := range t.Members {
		if !seen[k] {
			rest = append(rest, k)
		}
	}
	sort.Strings(rest)
	return append(out, rest...)
}

func bindingFlow(mb redfish.MemberBinding) string {
	var parts []string
	add := func(k, v string) { parts = append(parts, k+": "+v) }
	if mb.Resource != "" {
		add("resource", yamlStr(mb.Resource))
	}
	if mb.Path != "" {
		add("path", yamlStr(mb.Path))
	}
	if mb.Agg != "" {
		add("agg", mb.Agg)
	}
	if mb.Exists != nil {
		add("exists", strconv.FormatBool(*mb.Exists))
	}
	if mb.Const != nil {
		add("const", scalarYAML(mb.Const))
	}
	if mb.Map != nil {
		keys := make([]string, 0, len(mb.Map))
		for k := range mb.Map {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		kv := make([]string, len(keys))
		for i, k := range keys {
			kv[i] = yamlStr(k) + ": " + scalarYAML(mb.Map[k])
		}
		add("map", "{"+strings.Join(kv, ", ")+"}")
	}
	if mb.Eq != nil {
		add("eq", scalarYAML(mb.Eq))
	}
	if mb.Scale != 0 {
		add("scale", strconv.FormatFloat(mb.Scale, 'g', -1, 64))
	}
	if mb.Offset != 0 {
		add("offset", strconv.FormatFloat(mb.Offset, 'g', -1, 64))
	}
	if mb.Rate {
		add("rate", "true")
	}
	if mb.Width != 0 {
		add("width", strconv.Itoa(mb.Width))
	}
	if mb.ScanClass != "" {
		add("scan-class", yamlStr(mb.ScanClass))
	}
	if mb.Derived != "" {
		add("derived", quote(mb.Derived))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func scalarYAML(v any) string {
	switch x := v.(type) {
	case bool:
		return strconv.FormatBool(x)
	case int:
		return strconv.Itoa(x)
	case int64:
		return strconv.FormatInt(x, 10)
	case uint64:
		return strconv.FormatUint(x, 10)
	case float64:
		return strconv.FormatFloat(x, 'g', -1, 64)
	case string:
		return yamlStr(x)
	}
	return quote(fmt.Sprint(v))
}

// plainRE is what may go unquoted inside a flow map: no ':', ',', '[', '{',
// '#', spaces or quotes.
var plainRE = regexp.MustCompile(`^[A-Za-z_/][A-Za-z0-9_./\-]*$`)

// yamlStr renders a string scalar that decodes back to the same string:
// plain when unambiguous, double-quoted otherwise — including the words
// YAML 1.1 tools read as booleans ("On", "Off", "Yes", "No"), because a
// Redfish PowerState of "On" must never become true in someone's linter.
func yamlStr(s string) string {
	if plainRE.MatchString(s) {
		switch strings.ToLower(s) {
		case "true", "false", "null", "yes", "no", "on", "off", "y", "n", "~":
			return quote(s)
		}
		return s
	}
	return quote(s)
}

func quote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`)
	return `"` + r.Replace(s) + `"`
}

// TagsYAML renders the tag file from the manifest alone, so `naut redfish
// tags` re-derives it byte for byte from a committed manifest: every
// struct tag (role input, its contract type, the device's name for the
// part as desc), each source's __Online / __LastPollMs companions, and any
// hand-added command tag (role output, init 0).
func TagsYAML(m redfish.Manifest) ([]byte, error) {
	header := []string{
		"Generated by `naut redfish import` from the BMC's Redfish tree. Do not edit —",
		"re-run the import, or `naut redfish tags redfish_manifest.yaml` to re-derive",
		"this file from the committed manifest. The struct types are in hw_types.st.",
		"",
		"Compose it into a project with:  tag-files: [tags/redfish.yaml]",
	}
	var out []tagfile.Tag
	for _, t := range m.Tags {
		desc := t.Desc
		if ty, ok := hw.TypeByName(t.Type); ok && desc == "" {
			desc = ty.Desc
		}
		out = append(out, tagfile.Tag{Name: t.Name, Role: "input", Type: t.Type, Desc: desc})
	}
	for _, s := range m.Sources {
		out = append(out,
			tagfile.Tag{Name: hw.OnlineTagName(s.ID), Role: "input", Desc: "BMC " + s.ID + " answered its last poll (driver-synthesised)"},
			tagfile.Tag{Name: hw.LastPollTagName(s.ID), Role: "input", Desc: "epoch ms of BMC " + s.ID + "'s last complete poll (driver-synthesised)"},
		)
	}
	for _, w := range m.Writes {
		out = append(out, tagfile.Tag{Name: w.Name, Role: "output", Init: 0,
			Desc: "reset " + w.Tag + ": 0 none, 1 On, 2 GracefulShutdown, 3 ForceOff, 4 GracefulRestart (sent once on change to non-zero)"})
	}
	return tagfile.Render(header, out)
}

// TypesST renders hw_types.st — the same bytes every IT importer writes,
// bar the header's importer name.
func TypesST() ([]byte, error) { return hw.TypesST("redfish") }
