// manifest.go is the committed description of what a project consumes over
// Modbus: the TCP sources (devices/gateways) and the tag bindings onto their
// tables. Generated by `naut modbus import`; validated offline in New so
// `naut check` and `build` pass with no device in sight.
//
// The YAML shapes carry NO yaml struct tags, so the on-disk keys are the
// lowercased Go field names ("unitid", "wordorder", "scanclass") —
// eip.Manifest's and sparkplug/host's convention exactly, decoded with
// KnownFields(true) semantics so a typo is an error rather than a silently
// dropped binding. Duration fields ("3s", "2.5s") are the one wrinkle:
// time.Duration doesn't parse YAML strings natively, so Source and
// TagBinding decode through shadow structs with a parsing Duration wrapper —
// the public fields stay plain time.Duration for every Go consumer.
package modbus

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"reflect"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// Manifest is one project's Modbus surface: the sources it polls and the tag
// bindings onto them. Shared with plan.go (block reads), driver.go (the
// loops) and codegen (the generator renders one of these).
type Manifest struct {
	Sources []Source
	Tags    []TagBinding
}

// Source is one Modbus TCP endpoint: a device, or one unit-id behind a
// gateway (Anybus fronting several Omrons uses one Source per Omron, same
// host, different UnitID). It is the device row on /api/drivers and the
// quality scope — a source that dies takes exactly its own tags Stale.
type Source struct {
	// ID names the source ("FTIR_I"): TagBinding.Source refers to it, and
	// the /api/drivers device row carries it.
	ID string
	// Host is the device address ("192.168.20.51").
	Host string
	// Port is the TCP port; 0 means 502.
	Port int
	// UnitID is the Modbus unit identifier (0 is legal — many plain TCP
	// devices use it; gateways route on it).
	UnitID uint8
	// WordOrder is the register order of multi-register values: "big"
	// (default) or "little" — tentacle's reverseWords. Per source because
	// the same hardware has shipped both ways (Anybus; brief §9 risk 2).
	WordOrder string
	// ByteOrder is the byte order within each register: "big" (default) or
	// "little" — tentacle's reverseBits.
	ByteOrder string
	// Timeout bounds each request; 0 means the driver default (3s).
	Timeout time.Duration
	// RetryMin/RetryMax bound the reconnect backoff (defaults 1s/60s) —
	// tentacle's retryMinDelay/retryMaxDelay semantics.
	RetryMin time.Duration
	RetryMax time.Duration
	// Enable optionally names a BOOL tag; when it is false the source is
	// parked — no connection, tags NotConnected/Stale (tentacle *_ENABLED).
	Enable string
	// MaxBlock caps one read to at most this many registers (or coils) for
	// devices that reject long reads (some ADAM firmware caps at 64).
	// 0 means the protocol maxima (125 registers / 2000 coils).
	MaxBlock int
}

// Addr is the dial address, applying the default port.
func (s Source) Addr() string {
	port := s.Port
	if port == 0 {
		port = 502
	}
	return fmt.Sprintf("%s:%d", s.Host, port)
}

// TagBinding maps one nautilus tag onto a span of one source's table.
type TagBinding struct {
	// Name is the nautilus tag (what ST declares under VAR_EXTERNAL and Go
	// reads from the tag store).
	Name string
	// Source is the Source.ID this binding polls.
	Source string
	// Table is "holding", "input", "coil" or "discrete".
	Table string
	// Address is the 0-based PDU address (tentacle's `register`). What a
	// vendor datasheet calls 40001 is holding address 0.
	Address uint16
	// Format is how the raw bits mean a value: int16 uint16 int32 uint32
	// float32 float64 bool bit:N (see ParseFormat). Coil/discrete tables
	// take only "bool" (or empty, which means bool).
	Format string
	// Scale/Offset scale reads and inverse-scale writes:
	// engineering = raw*Scale + Offset. Scale 0 means 1.
	Scale  float64
	Offset float64
	// Writable makes this an output tag: the runtime's writes propagate to
	// the device (FC 5/6/15/16). Only holding and coil tables are writable.
	Writable bool
	// Rewrite > 0 re-asserts the last commanded value on this period even
	// when unchanged — the keep-alive devices like the Banner SC10 and the
	// AL1352 watchdog depend on. Default 0: change-only.
	Rewrite time.Duration
	// ScanClass names the poll group; "" is the default class and NoPoll
	// catalogs the tag without polling it. WithTagClass overrides this, so
	// generated manifests stay regenerable and policy lives in main.go.
	ScanClass string
	// WriteOnly opts a writable binding out of the read plan for registers
	// that cannot be read back (rare; some i550 control words). Without it
	// a writable binding is also polled, and the read-back is the source of
	// truth after a restart.
	WriteOnly bool
}

// ── YAML ─────────────────────────────────────────────────────────────────

// LoadManifest decodes a modbus_manifest.yaml. It does not validate — call
// Validate (New does, through BuildPlan) for the cross-references, since a
// generator may want to load, edit and re-render a manifest that is not yet
// consistent.
func LoadManifest(r io.Reader) (Manifest, error) {
	var m Manifest
	dec := yaml.NewDecoder(r)
	dec.KnownFields(true) // a typo is an error, not a silently dropped binding
	if err := dec.Decode(&m); err != nil {
		if errors.Is(err, io.EOF) {
			return Manifest{}, fmt.Errorf("modbus: manifest is empty")
		}
		return Manifest{}, fmt.Errorf("modbus: manifest: %w", err)
	}
	return m, nil
}

// ParseManifest decodes a manifest from bytes — LoadManifest for callers
// that already hold the file (the project loader reads through an fs.FS).
func ParseManifest(data []byte) (Manifest, error) {
	return LoadManifest(bytes.NewReader(data))
}

// duration parses "100ms" / "2.5s" yaml scalars, like the project
// manifest's Duration — kept package-private because the public structs
// carry plain time.Duration.
type duration time.Duration

func (d *duration) UnmarshalYAML(node *yaml.Node) error {
	v, err := time.ParseDuration(node.Value)
	if err != nil {
		return fmt.Errorf("bad duration %q (want e.g. 100ms, 2s)", node.Value)
	}
	*d = duration(v)
	return nil
}

func (d duration) MarshalYAML() (any, error) {
	return time.Duration(d).String(), nil
}

// sourceYAML mirrors Source with parseable duration fields. Field names
// must stay identical to Source's — the lowercased names ARE the on-disk
// keys, and the copy below is by name.
type sourceYAML struct {
	ID        string
	Host      string
	Port      int
	UnitID    uint8
	WordOrder string
	ByteOrder string
	Timeout   duration
	RetryMin  duration
	RetryMax  duration
	Enable    string
	MaxBlock  int
}

// UnmarshalYAML decodes through the shadow struct. strictDecode re-imposes
// KnownFields, which a custom unmarshaler otherwise silently loses
// (yaml.v3's KnownFields is a property of the decoder, and node.Decode
// builds a fresh one).
func (s *Source) UnmarshalYAML(node *yaml.Node) error {
	var r sourceYAML
	if err := strictDecode(node, &r); err != nil {
		return err
	}
	*s = Source{
		ID: r.ID, Host: r.Host, Port: r.Port, UnitID: r.UnitID,
		WordOrder: r.WordOrder, ByteOrder: r.ByteOrder,
		Timeout: time.Duration(r.Timeout), RetryMin: time.Duration(r.RetryMin),
		RetryMax: time.Duration(r.RetryMax), Enable: r.Enable, MaxBlock: r.MaxBlock,
	}
	return nil
}

// MarshalYAML renders through the same shadow, so a loaded manifest
// re-renders with the keys it was read with (durations as "3s", not
// nanosecond integers).
func (s Source) MarshalYAML() (any, error) {
	return sourceYAML{
		ID: s.ID, Host: s.Host, Port: s.Port, UnitID: s.UnitID,
		WordOrder: s.WordOrder, ByteOrder: s.ByteOrder,
		Timeout: duration(s.Timeout), RetryMin: duration(s.RetryMin),
		RetryMax: duration(s.RetryMax), Enable: s.Enable, MaxBlock: s.MaxBlock,
	}, nil
}

// tagYAML mirrors TagBinding, as sourceYAML mirrors Source.
type tagYAML struct {
	Name      string
	Source    string
	Table     string
	Address   uint16
	Format    string
	Scale     float64
	Offset    float64
	Writable  bool
	Rewrite   duration
	ScanClass string
	WriteOnly bool
}

func (t *TagBinding) UnmarshalYAML(node *yaml.Node) error {
	var r tagYAML
	if err := strictDecode(node, &r); err != nil {
		return err
	}
	*t = TagBinding{
		Name: r.Name, Source: r.Source, Table: r.Table, Address: r.Address,
		Format: r.Format, Scale: r.Scale, Offset: r.Offset,
		Writable: r.Writable, Rewrite: time.Duration(r.Rewrite),
		ScanClass: r.ScanClass, WriteOnly: r.WriteOnly,
	}
	return nil
}

func (t TagBinding) MarshalYAML() (any, error) {
	return tagYAML{
		Name: t.Name, Source: t.Source, Table: t.Table, Address: t.Address,
		Format: t.Format, Scale: t.Scale, Offset: t.Offset,
		Writable: t.Writable, Rewrite: duration(t.Rewrite),
		ScanClass: t.ScanClass, WriteOnly: t.WriteOnly,
	}, nil
}

// strictDecode decodes node into v and rejects any key the struct does not
// declare — acceptance/spec.go's trick, because KnownFields does not survive
// into a custom UnmarshalYAML.
func strictDecode(node *yaml.Node, v any) error {
	if err := node.Decode(v); err != nil {
		return err
	}
	if node.Kind != yaml.MappingNode {
		return nil
	}
	t := reflect.TypeOf(v).Elem()
	known := make(map[string]bool, t.NumField())
	names := make([]string, 0, t.NumField())
	for i := range t.NumField() {
		name := strings.ToLower(t.Field(i).Name)
		known[name] = true
		names = append(names, name)
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if k := node.Content[i]; !known[k.Value] {
			return fmt.Errorf("line %d: unknown key %q%s", k.Line, k.Value, didYouMean(k.Value, names))
		}
	}
	return nil
}

// ── Validation ───────────────────────────────────────────────────────────

// Table names. Holding and coil are writable; input and discrete are
// read-only by the protocol itself.
const (
	TableHolding  = "holding"
	TableInput    = "input"
	TableCoil     = "coil"
	TableDiscrete = "discrete"
)

var tableNames = []string{TableHolding, TableInput, TableCoil, TableDiscrete}

// registerTable reports whether the table holds 16-bit registers (as
// opposed to single bits).
func registerTable(table string) bool {
	return table == TableHolding || table == TableInput
}

// writableTable reports whether the protocol can write the table at all.
func writableTable(table string) bool {
	return table == TableHolding || table == TableCoil
}

// Validate checks the manifest offline: every reference resolves, every
// format parses, nothing overlaps incoherently. It is the whole of what
// `naut check` needs — no device is ever contacted. All findings are
// reported at once (errors.Join) so a generated manifest with three
// problems is three lines, not three edit-run cycles.
func (m Manifest) Validate() error {
	var errs []error

	byID := make(map[string]Source, len(m.Sources))
	ids := make([]string, 0, len(m.Sources))
	for _, s := range m.Sources {
		if s.ID == "" {
			errs = append(errs, fmt.Errorf("source with host %q: missing id", s.Host))
			continue
		}
		if _, dup := byID[s.ID]; dup {
			errs = append(errs, fmt.Errorf("duplicate source id %q", s.ID))
			continue
		}
		byID[s.ID] = s
		ids = append(ids, s.ID)
		if s.Host == "" {
			errs = append(errs, fmt.Errorf("source %s: missing host", s.ID))
		}
		if s.WordOrder != "" && s.WordOrder != OrderBig && s.WordOrder != OrderLittle {
			errs = append(errs, fmt.Errorf("source %s: wordorder %q (want big or little)", s.ID, s.WordOrder))
		}
		if s.ByteOrder != "" && s.ByteOrder != OrderBig && s.ByteOrder != OrderLittle {
			errs = append(errs, fmt.Errorf("source %s: byteorder %q (want big or little)", s.ID, s.ByteOrder))
		}
		if s.Timeout < 0 || s.RetryMin < 0 || s.RetryMax < 0 {
			errs = append(errs, fmt.Errorf("source %s: negative duration", s.ID))
		}
		if s.RetryMin > 0 && s.RetryMax > 0 && s.RetryMin > s.RetryMax {
			errs = append(errs, fmt.Errorf("source %s: retrymin %v exceeds retrymax %v", s.ID, s.RetryMin, s.RetryMax))
		}
		if s.MaxBlock < 0 {
			errs = append(errs, fmt.Errorf("source %s: negative maxblock", s.ID))
		}
	}

	seen := make(map[string]bool, len(m.Tags))
	for _, t := range m.Tags {
		if t.Name == "" {
			errs = append(errs, fmt.Errorf("tag binding on source %q: missing name", t.Source))
			continue
		}
		if seen[t.Name] {
			errs = append(errs, fmt.Errorf("duplicate tag name %q", t.Name))
			continue
		}
		seen[t.Name] = true

		if _, ok := byID[t.Source]; !ok {
			errs = append(errs, fmt.Errorf("tag %s: unknown source %q%s", t.Name, t.Source, didYouMean(t.Source, ids)))
		}
		table := t.Table
		if !registerTable(table) && table != TableCoil && table != TableDiscrete {
			errs = append(errs, fmt.Errorf("tag %s: unknown table %q%s", t.Name, table, didYouMean(table, tableNames)))
			continue
		}
		f, err := t.format()
		if err != nil {
			errs = append(errs, fmt.Errorf("tag %s: %w", t.Name, err))
			continue
		}
		if !registerTable(table) && f.Kind != "bool" {
			errs = append(errs, fmt.Errorf("tag %s: format %s on %s table (bit tables take bool)", t.Name, f, table))
		}
		if t.Writable && !writableTable(table) {
			errs = append(errs, fmt.Errorf("tag %s: writable on read-only %s table (use holding or coil)", t.Name, table))
		}
		if !t.Writable && t.Rewrite > 0 {
			errs = append(errs, fmt.Errorf("tag %s: rewrite without writable", t.Name))
		}
		if !t.Writable && t.WriteOnly {
			errs = append(errs, fmt.Errorf("tag %s: writeonly without writable", t.Name))
		}
		if int(t.Address)+f.Words() > 0x10000 {
			errs = append(errs, fmt.Errorf("tag %s: address %d + %d registers exceeds the 16-bit address space", t.Name, t.Address, f.Words()))
		}
	}

	errs = append(errs, m.overlapErrors()...)
	if len(errs) == 0 {
		return nil
	}
	return errors.Join(errs...)
}

// format parses the binding's format, defaulting empty to bool on bit
// tables (a coil binding's format is self-evident).
func (t TagBinding) format() (Format, error) {
	if t.Format == "" && (t.Table == TableCoil || t.Table == TableDiscrete) {
		return Format{Kind: "bool"}, nil
	}
	return ParseFormat(t.Format)
}

// overlapErrors flags bindings on the same (source, table) whose register
// spans intersect incoherently. Two bindings MAY share an address when both
// are single-word — a status word read as uint16 alongside its bit:N flags,
// or two aliases of the same register — because both read the same 16 bits
// and cannot disagree about layout. A partial overlap, or a multi-word
// overlap of different formats, means one of the addresses is wrong: a
// float32 straddling someone else's int16 mis-decodes both.
func (m Manifest) overlapErrors() []error {
	type span struct {
		t TagBinding
		f Format
	}
	groups := map[string][]span{}
	for _, t := range m.Tags {
		f, err := t.format()
		if err != nil {
			continue // reported by Validate already
		}
		key := t.Source + "\x00" + t.Table
		groups[key] = append(groups[key], span{t, f})
	}
	var errs []error
	for _, g := range groups {
		for i := 0; i < len(g); i++ {
			for j := i + 1; j < len(g); j++ {
				a, b := g[i], g[j]
				// Bit tables: one address is one bit; only identity overlaps.
				if !registerTable(a.t.Table) {
					continue
				}
				aEnd := int(a.t.Address) + a.f.Words()
				bEnd := int(b.t.Address) + b.f.Words()
				if int(b.t.Address) >= aEnd || int(a.t.Address) >= bEnd {
					continue // disjoint
				}
				if a.t.Address == b.t.Address &&
					(a.f == b.f || (a.f.Words() == 1 && b.f.Words() == 1)) {
					continue // same word(s), coherent layouts
				}
				errs = append(errs, fmt.Errorf(
					"tags %s (%s@%d %s) and %s (%s@%d %s) overlap with different layouts",
					a.t.Name, a.t.Table, a.t.Address, a.f,
					b.t.Name, b.t.Table, b.t.Address, b.f))
			}
		}
	}
	return errs
}
