// manifest.go is the committed description of what a project polls over
// SNMP: the agents (sources) with their transport and credential NAMES, the
// struct tags with one explicit OID binding per member, and the opt-in
// command writes. Generated by `naut snmp import`; validated offline in New
// so `naut check` and `build` pass with no device — and no secret — in
// sight (docs/design/it-drivers.md §6.1).
//
// The on-disk keys are the brief's hyphenated ones (community-env,
// max-repetitions, stale-after, scan-class), so unlike modbus the YAML
// mirrors carry struct tags; the public structs stay tag-free and are
// filled from the mirrors. The whole file is decoded by ONE decoder with
// KnownFields(true) and no custom mapping unmarshalers, so a typo anywhere —
// a source key, a member key, a binding key inherited from hw.Binding — is
// an error with a line number rather than a silently dropped binding.
//
// Secrets never appear here: a community or a v3 pass phrase is named by
// `*-env: VAR` or `*-file: path` and read when the driver connects.
package snmp

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/joyautomation/nautilus/hw"
	"github.com/joyautomation/nautilus/snmp/walk"
	"gopkg.in/yaml.v3"
)

// Defaults per source (brief §3.1).
const (
	DefaultPort           = 161
	DefaultTimeout        = 3 * time.Second
	DefaultRetries        = 2
	DefaultMaxRepetitions = 20
)

// Protocol versions, auth and priv protocol names as the manifest spells them.
const (
	V2c = "2c"
	V3  = "3"

	AuthSHA1   = "sha1"
	AuthSHA256 = "sha256"
	AuthMD5    = "md5" // accepted with a warning

	PrivAES128  = "aes128"
	PrivAES256  = "aes256"  // Blumenthal key extension (draft-blumenthal-aes-usm)
	PrivAES256C = "aes256c" // Reeder ("Cisco") key extension
	PrivDES     = "des"     // accepted with a warning
)

// Manifest is one project's SNMP surface.
type Manifest struct {
	Sources []Source
	Tags    []Tag
	Writes  []Write
}

// Source is one SNMP agent: a switch, a PDU, a UPS. It is the device row on
// /api/drivers and the quality scope.
type Source struct {
	ID   string
	Host string
	Port int // 0 = 161

	// Version is "2c" (default) or "3".
	Version string
	// v2c: the community, by name.
	CommunityEnv  string
	CommunityFile string
	// v3 USM. Auth "" is noAuthNoPriv; Auth without Priv is authNoPriv.
	User     string
	Auth     string // sha1 | sha256 | md5
	AuthEnv  string
	AuthFile string
	Priv     string // aes128 | aes256 | aes256c | des
	PrivEnv  string
	PrivFile string
	// Context is the v3 contextName, for agents that serve several views
	// (per-VLAN bridge MIBs, a simulator's data files). Usually empty.
	Context string

	Timeout time.Duration // per request; 0 = 3s
	// Retries per request after the first try; nil = 2.
	Retries *int
	// MaxRepetitions per GetBulk; 0 = 20. Some agents choke above 10.
	MaxRepetitions int
	// Interval is this source's default-class poll period; 0 takes the
	// driver's scan rate.
	Interval   time.Duration
	StaleAfter time.Duration // 0 = 3×Interval
	// Enable optionally names a BOOL tag; false parks the source.
	Enable string
}

// Addr is the host:port the source is polled at.
func (s Source) Addr() string {
	port := s.Port
	if port == 0 {
		port = DefaultPort
	}
	return fmt.Sprintf("%s:%d", s.Host, port)
}

func (s Source) version() string {
	if s.Version == "" {
		return V2c
	}
	return s.Version
}

func (s Source) timeout() time.Duration {
	if s.Timeout <= 0 {
		return DefaultTimeout
	}
	return s.Timeout
}

func (s Source) retries() int {
	if s.Retries == nil {
		return DefaultRetries
	}
	return *s.Retries
}

func (s Source) maxRepetitions() int {
	if s.MaxRepetitions <= 0 {
		return DefaultMaxRepetitions
	}
	return s.MaxRepetitions
}

// Tag is one struct tag: a contract type (hw.Types), the source it polls,
// and one binding per member it fills.
type Tag struct {
	Name    string
	Type    string
	Source  string
	Members map[string]Member
}

// Member is one member binding: the fully instanced numeric OID it reads,
// plus the shared vocabulary (const, map, eq, scale, offset, rate, width,
// scan-class, derived). Const and derived members carry no OID.
type Member struct {
	OID string
	hw.Binding
}

// Write is one opt-in command: a scalar output tag whose value, on change,
// is SET to OID. Set maps the command value (its string form: "true",
// "false", "3") to the INTEGER put on the wire — {true: 1, false: 2} for a
// CyberPower outlet (immediateOn / immediateOff); without Set, an INT
// command is written as itself and a BOOL as 1/0.
type Write struct {
	Name   string
	Tag    string
	Member string
	OID    string
	Set    map[string]int64
}

// ── YAML ─────────────────────────────────────────────────────────────────

type manifestYAML struct {
	Sources []sourceYAML `yaml:"sources"`
	Tags    []tagYAML    `yaml:"tags"`
	Writes  []writeYAML  `yaml:"writes"`
}

type sourceYAML struct {
	ID             string   `yaml:"id"`
	Host           string   `yaml:"host"`
	Port           int      `yaml:"port"`
	Version        string   `yaml:"version"`
	CommunityEnv   string   `yaml:"community-env"`
	CommunityFile  string   `yaml:"community-file"`
	User           string   `yaml:"user"`
	Auth           string   `yaml:"auth"`
	AuthEnv        string   `yaml:"auth-env"`
	AuthFile       string   `yaml:"auth-file"`
	Priv           string   `yaml:"priv"`
	PrivEnv        string   `yaml:"priv-env"`
	PrivFile       string   `yaml:"priv-file"`
	Context        string   `yaml:"context"`
	Timeout        duration `yaml:"timeout"`
	Retries        *int     `yaml:"retries"`
	MaxRepetitions int      `yaml:"max-repetitions"`
	Interval       duration `yaml:"interval"`
	StaleAfter     duration `yaml:"stale-after"`
	Enable         string   `yaml:"enable"`
}

type tagYAML struct {
	Name    string                `yaml:"name"`
	Type    string                `yaml:"type"`
	Source  string                `yaml:"source"`
	Members map[string]memberYAML `yaml:"members"`
}

type memberYAML struct {
	OID        string `yaml:"oid"`
	hw.Binding `yaml:",inline"`
}

type writeYAML struct {
	Name   string           `yaml:"name"`
	Tag    string           `yaml:"tag"`
	Member string           `yaml:"member"`
	OID    string           `yaml:"oid"`
	Set    map[string]int64 `yaml:"set"`
}

// duration parses "3s" / "500ms".
type duration time.Duration

func (d *duration) UnmarshalYAML(node *yaml.Node) error {
	v, err := time.ParseDuration(node.Value)
	if err != nil {
		return fmt.Errorf("line %d: bad duration %q (want e.g. 3s, 500ms)", node.Line, node.Value)
	}
	*d = duration(v)
	return nil
}

// LoadManifest decodes an snmp_manifest.yaml. It does not validate — New
// does (Validate), so a generator can load, edit and re-render a manifest
// that is not yet consistent.
func LoadManifest(r io.Reader) (Manifest, error) {
	var y manifestYAML
	dec := yaml.NewDecoder(r)
	dec.KnownFields(true)
	if err := dec.Decode(&y); err != nil {
		if errors.Is(err, io.EOF) {
			return Manifest{}, fmt.Errorf("snmp: manifest is empty")
		}
		return Manifest{}, fmt.Errorf("snmp: manifest: %w", err)
	}
	var m Manifest
	for _, s := range y.Sources {
		m.Sources = append(m.Sources, Source{
			ID: s.ID, Host: s.Host, Port: s.Port, Version: s.Version,
			CommunityEnv: s.CommunityEnv, CommunityFile: s.CommunityFile,
			User: s.User, Auth: s.Auth, AuthEnv: s.AuthEnv, AuthFile: s.AuthFile,
			Priv: s.Priv, PrivEnv: s.PrivEnv, PrivFile: s.PrivFile, Context: s.Context,
			Timeout: time.Duration(s.Timeout), Retries: s.Retries,
			MaxRepetitions: s.MaxRepetitions, Interval: time.Duration(s.Interval),
			StaleAfter: time.Duration(s.StaleAfter), Enable: s.Enable,
		})
	}
	for _, t := range y.Tags {
		tag := Tag{Name: t.Name, Type: t.Type, Source: t.Source, Members: map[string]Member{}}
		for k, v := range t.Members {
			tag.Members[k] = Member{OID: v.OID, Binding: v.Binding}
		}
		m.Tags = append(m.Tags, tag)
	}
	for _, w := range y.Writes {
		m.Writes = append(m.Writes, Write{Name: w.Name, Tag: w.Tag, Member: w.Member, OID: w.OID, Set: w.Set})
	}
	return m, nil
}

// ParseManifest is LoadManifest over bytes.
func ParseManifest(data []byte) (Manifest, error) { return LoadManifest(bytes.NewReader(data)) }

// ── validation ─────────────────────────────────────────────────────────

// Validate checks everything the SNMP layer owns, offline: sources, their
// credential NAMES (never their values), OID syntax, and the binding shape
// per member (hw.Binding.Validate against the contract field). The
// cross-references hw owns — unknown type, unknown member, derived names —
// are checked again by hw.NewBase inside New; checking the member here too
// makes a generator's error name the OID. All findings at once.
func (m Manifest) Validate() error {
	var errs []error
	ids := map[string]bool{}
	for i, s := range m.Sources {
		if s.ID == "" {
			errs = append(errs, fmt.Errorf("source #%d (host %q): missing id", i+1, s.Host))
			continue
		}
		if ids[s.ID] {
			errs = append(errs, fmt.Errorf("duplicate source id %q", s.ID))
			continue
		}
		ids[s.ID] = true
		errs = append(errs, s.validate()...)
	}

	names := map[string]bool{}
	for _, t := range m.Tags {
		if t.Name == "" {
			errs = append(errs, fmt.Errorf("a tag on source %q has no name", t.Source))
			continue
		}
		if names[t.Name] {
			errs = append(errs, fmt.Errorf("duplicate tag %q", t.Name))
			continue
		}
		names[t.Name] = true
		if !ids[t.Source] {
			errs = append(errs, fmt.Errorf("tag %s: unknown source %q", t.Name, t.Source))
		}
		if _, ok := hw.TypeByName(t.Type); !ok {
			errs = append(errs, fmt.Errorf("tag %s: unknown type %q (the IT-hardware set is %s)", t.Name, t.Type, hw.TypeNames()))
			continue
		}
		for _, mname := range sortedKeys(t.Members) {
			mb := t.Members[mname]
			_, f, ok := hw.FieldOf(t.Type, mname)
			if !ok {
				errs = append(errs, fmt.Errorf("tag %s: type %s has no member %q", t.Name, t.Type, mname))
				continue
			}
			if err := mb.Binding.Validate(f); err != nil {
				errs = append(errs, fmt.Errorf("tag %s: %w", t.Name, err))
				continue
			}
			switch {
			case mb.IsStatic() && mb.OID != "":
				errs = append(errs, fmt.Errorf("tag %s: member %s: oid: with const/derived — a static member polls nothing", t.Name, mname))
			case !mb.IsStatic() && mb.OID == "":
				errs = append(errs, fmt.Errorf("tag %s: member %s: needs an oid (or const/derived)", t.Name, mname))
			case !mb.IsStatic():
				if _, err := walk.ParseOID(mb.OID); err != nil {
					errs = append(errs, fmt.Errorf("tag %s: member %s: %w", t.Name, mname, err))
				}
			}
		}
	}

	wnames := map[string]bool{}
	for _, w := range m.Writes {
		if w.Name == "" {
			errs = append(errs, fmt.Errorf("a write on tag %q has no name", w.Tag))
			continue
		}
		if wnames[w.Name] {
			errs = append(errs, fmt.Errorf("duplicate write %q", w.Name))
			continue
		}
		wnames[w.Name] = true
		if w.OID == "" {
			errs = append(errs, fmt.Errorf("write %s: needs an oid", w.Name))
		} else if _, err := walk.ParseOID(w.OID); err != nil {
			errs = append(errs, fmt.Errorf("write %s: %w", w.Name, err))
		}
		for k := range w.Set {
			if k == "" {
				errs = append(errs, fmt.Errorf("write %s: set: has an empty key", w.Name))
			}
		}
	}
	return errors.Join(errs...)
}

func (s Source) validate() []error {
	var errs []error
	bad := func(format string, a ...any) {
		errs = append(errs, fmt.Errorf("source %s: "+format, append([]any{s.ID}, a...)...))
	}
	if s.Host == "" {
		bad("missing host")
	}
	if s.Port < 0 || s.Port > 65535 {
		bad("port %d out of range", s.Port)
	}
	if s.Timeout < 0 || s.Interval < 0 || s.StaleAfter < 0 {
		bad("negative duration")
	}
	if s.Retries != nil && *s.Retries < 0 {
		bad("retries must be 0 or more")
	}
	if s.MaxRepetitions < 0 {
		bad("max-repetitions must be positive")
	}
	pair := func(key, env, file string) {
		if env != "" && file != "" {
			bad("%s-env and %s-file are alternatives — set one", key, key)
		}
	}
	switch s.version() {
	case V2c:
		pair("community", s.CommunityEnv, s.CommunityFile)
		if s.CommunityEnv == "" && s.CommunityFile == "" {
			bad("version 2c needs community-env or community-file (the community is a secret: never inline it)")
		}
		if s.User != "" || s.Auth != "" || s.Priv != "" || s.AuthEnv != "" || s.AuthFile != "" || s.PrivEnv != "" || s.PrivFile != "" || s.Context != "" {
			bad("user/auth/priv/context are SNMPv3 keys — set version: 3, or drop them")
		}
	case V3:
		if s.CommunityEnv != "" || s.CommunityFile != "" {
			bad("community-env/community-file are v2c keys; v3 authenticates with user/auth/priv")
		}
		if s.User == "" {
			bad("version 3 needs user")
		}
		switch s.Auth {
		case "", AuthSHA1, AuthSHA256, AuthMD5:
		default:
			bad("auth %q (want sha1, sha256 or md5)", s.Auth)
		}
		switch s.Priv {
		case "", PrivAES128, PrivAES256, PrivAES256C, PrivDES:
		default:
			bad("priv %q (want aes128, aes256, aes256c or des)", s.Priv)
		}
		pair("auth", s.AuthEnv, s.AuthFile)
		pair("priv", s.PrivEnv, s.PrivFile)
		if s.Auth != "" && s.AuthEnv == "" && s.AuthFile == "" {
			bad("auth: %s needs auth-env or auth-file", s.Auth)
		}
		if s.Auth == "" && (s.AuthEnv != "" || s.AuthFile != "") {
			bad("auth-env/auth-file without auth: (name the protocol: sha256)")
		}
		if s.Priv != "" && s.Auth == "" {
			bad("priv without auth — USM has no privacy without authentication")
		}
		if s.Priv != "" && s.PrivEnv == "" && s.PrivFile == "" {
			bad("priv: %s needs priv-env or priv-file", s.Priv)
		}
		if s.Priv == "" && (s.PrivEnv != "" || s.PrivFile != "") {
			bad("priv-env/priv-file without priv: (name the protocol: aes128)")
		}
	default:
		bad("version %q (want 2c or 3)", s.Version)
	}
	return errs
}

// Warnings are the conditions `naut check` reports without failing: a
// credential variable or file that is not present HERE (check runs on
// laptops and in CI without the secrets), and the legacy MD5/DES protocols
// half the PDUs on the market still ship with. Messages name variables and
// paths, never values.
func (m Manifest) Warnings() []string {
	var out []string
	for _, s := range m.Sources {
		for _, c := range s.credentials() {
			if c.env != "" {
				if v, ok := os.LookupEnv(c.env); !ok || v == "" {
					out = append(out, fmt.Sprintf("source %s: %s-env: $%s is not set here — the driver will fail to connect until it is", s.ID, c.key, c.env))
				}
			}
			if c.file != "" {
				if _, err := os.Stat(c.file); err != nil {
					out = append(out, fmt.Sprintf("source %s: %s-file: %s is not readable here (%s)", s.ID, c.key, c.file, errKind(err)))
				}
			}
		}
		if s.version() == V3 {
			if s.Auth == AuthMD5 {
				out = append(out, fmt.Sprintf("source %s: auth md5 is broken cryptography — use sha256 if the device offers it", s.ID))
			}
			if s.Priv == PrivDES {
				out = append(out, fmt.Sprintf("source %s: priv des is broken cryptography — use aes128 if the device offers it", s.ID))
			}
			if s.Auth == "" {
				out = append(out, fmt.Sprintf("source %s: v3 noAuthNoPriv sends everything in the clear", s.ID))
			}
		}
	}
	return out
}

func errKind(err error) string {
	switch {
	case errors.Is(err, os.ErrNotExist):
		return "does not exist"
	case errors.Is(err, os.ErrPermission):
		return "permission denied"
	}
	return "unreadable"
}

type credential struct{ key, env, file string }

func (s Source) credentials() []credential {
	var out []credential
	if s.version() == V2c {
		if s.CommunityEnv != "" || s.CommunityFile != "" {
			out = append(out, credential{"community", s.CommunityEnv, s.CommunityFile})
		}
		return out
	}
	if s.Auth != "" {
		out = append(out, credential{"auth", s.AuthEnv, s.AuthFile})
	}
	if s.Priv != "" {
		out = append(out, credential{"priv", s.PrivEnv, s.PrivFile})
	}
	return out
}

// resolve reads one secret by its name at connect time: the variable, or
// the file with its trailing newline trimmed (a k8s Secret mount usually
// has one). The error names where it looked, never what it found.
func (c credential) resolve(sourceID string) (string, error) {
	if c.env != "" {
		v, ok := os.LookupEnv(c.env)
		if !ok || v == "" {
			return "", fmt.Errorf("source %s: %s-env: $%s is not set", sourceID, c.key, c.env)
		}
		return v, nil
	}
	b, err := os.ReadFile(c.file)
	if err != nil {
		return "", fmt.Errorf("source %s: %s-file: %s %s", sourceID, c.key, c.file, errKind(err))
	}
	v := strings.TrimRight(string(b), "\r\n")
	if v == "" {
		return "", fmt.Errorf("source %s: %s-file: %s is empty", sourceID, c.key, c.file)
	}
	return v, nil
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
