package main

// `nautilus tags import-csv` — the third generator kind (docs/design/tags.md
// §2.1). The other two are the protocol importer (`eip import`, which browses
// a controller) and a project's own config-table expander, which is bespoke
// and belongs in that project rather than in this tool.
//
// CSV earns a shipped tool where a config table does not: the FORMAT is
// standard even though every plant's columns differ, so a column mapping is
// the entire difference between one project's export and another's. That is a
// stable contract; "whatever shape this integrator's spreadsheet is" is not.

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/joyautomation/nautilus/internal/tagfile"
)

const tagsUsage = `nautilus tags — generate a tag file from a spreadsheet export

Usage:
  nautilus tags import-csv [flags] <file.csv>

Reads a CSV with a header row and writes a nautilus tag file, which a project
composes with:  tag-files: [tags/plant.yaml]

Column flags name the COLUMN each field comes from; a column that is absent
is simply not emitted. Defaults match the field names.
  --name       column holding the tag name       (default "name")
  --role       column holding the role           (default "role")
  --type       column holding a UDT name         (default "type")
  --init       column holding the initial value  (default "init")
  --unit       column holding the engineering unit (default "unit")
  --desc       column holding the description    (default "desc")
  --role-default  role for rows with no role column (default "input")
  -o           output path (default "tags/imported.yaml")
`

func runTags(args []string) int {
	if len(args) < 1 {
		fmt.Fprint(os.Stderr, tagsUsage)
		return 2
	}
	switch args[0] {
	case "import-csv":
		return runTagsImportCSV(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "nautilus tags: unknown subcommand %q\n\n%s", args[0], tagsUsage)
		return 2
	}
}

func runTagsImportCSV(args []string) int {
	fs := flag.NewFlagSet("tags import-csv", flag.ContinueOnError)
	nameCol := fs.String("name", "name", "column holding the tag name")
	roleCol := fs.String("role", "role", "column holding the role")
	typeCol := fs.String("type", "type", "column holding a UDT name")
	initCol := fs.String("init", "init", "column holding the initial value")
	unitCol := fs.String("unit", "unit", "column holding the engineering unit")
	descCol := fs.String("desc", "desc", "column holding the description")
	roleDefault := fs.String("role-default", "input", "role for rows with no role column")
	out := fs.String("o", "tags/imported.yaml", "output tag file")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if fs.NArg() != 1 {
		fmt.Fprint(os.Stderr, tagsUsage)
		return 2
	}
	src := fs.Arg(0)

	f, err := os.Open(src)
	if err != nil {
		fmt.Fprintln(os.Stderr, "nautilus tags:", err)
		return 1
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.TrimLeadingSpace = true
	r.FieldsPerRecord = -1 // ragged rows are reported per-row, with the row number
	head, err := r.Read()
	if err != nil {
		fmt.Fprintln(os.Stderr, "nautilus tags: reading the header row:", err)
		return 1
	}
	col := map[string]int{}
	for i, h := range head {
		col[strings.TrimSpace(h)] = i
	}
	if _, ok := col[*nameCol]; !ok {
		fmt.Fprintf(os.Stderr, "nautilus tags: %s has no %q column (found: %s)\n",
			src, *nameCol, strings.Join(head, ", "))
		return 1
	}

	get := func(rec []string, name string) string {
		i, ok := col[name]
		if !ok || i >= len(rec) {
			return ""
		}
		return strings.TrimSpace(rec[i])
	}

	var tags []tagfile.Tag
	for row := 2; ; row++ {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			fmt.Fprintf(os.Stderr, "nautilus tags: %s:%d: %v\n", src, row, err)
			return 1
		}
		name := get(rec, *nameCol)
		if name == "" {
			continue // a blank line, or a spacer row in the spreadsheet
		}
		t := tagfile.Tag{
			Name: name,
			Role: *roleDefault,
			Type: get(rec, *typeCol),
			Unit: get(rec, *unitCol),
			Desc: get(rec, *descCol),
		}
		if role := get(rec, *roleCol); role != "" {
			t.Role = strings.ToLower(role)
		}
		if raw := get(rec, *initCol); raw != "" {
			t.Init = parseInit(raw)
		}
		tags = append(tags, t)
	}
	if len(tags) == 0 {
		fmt.Fprintf(os.Stderr, "nautilus tags: %s has a header but no rows with a %q\n", src, *nameCol)
		return 1
	}

	raw, err := tagfile.Render([]string{
		fmt.Sprintf("Generated by `nautilus tags import-csv` from %s.", filepath.Base(src)),
		"Do not edit — change the spreadsheet and re-run.",
		"",
		fmt.Sprintf("Compose it into a project with:  tag-files: [%s]", *out),
	}, tags)
	if err != nil {
		fmt.Fprintln(os.Stderr, "nautilus tags:", err)
		return 1
	}
	if dir := filepath.Dir(*out); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "nautilus tags:", err)
			return 1
		}
	}
	if err := os.WriteFile(*out, raw, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "nautilus tags:", err)
		return 1
	}
	fmt.Printf("wrote %s (%d tags) — compose it with `tag-files: [%s]`\n", *out, len(tags), *out)
	fmt.Printf("run `nautilus check` to verify it against your programs\n")
	return 0
}

// parseInit keeps a spreadsheet cell in the type the tag store expects. A
// number stays a number and a bool stays a bool; anything else is a string,
// because guessing is worse than being literal about what the cell said.
//
// Whole numbers become floats, matching the manifest loader: YAML decodes 65
// as int and 65.0 as float64, and an ST REAL tag wants the latter.
func parseInit(s string) any {
	switch strings.ToLower(s) {
	case "true":
		return true
	case "false":
		return false
	}
	if f, err := strconv.ParseFloat(s, 64); err == nil {
		return f
	}
	return s
}
