package host

import (
	"strings"
	"testing"

	"github.com/joyautomation/nautilus/lang/ir"
	"github.com/joyautomation/nautilus/sparkplug/spb"
)

// sampleManifest is the manifest from docs/design/sparkplug-host.md §5, in the
// flow style the doc shows. The generator emits block style; both decode the
// same, and this is the shape the whole package is specified against.
const sampleManifest = `
# Generated by ` + "`nautilus sparkplug import --broker tcp://mqtt.pomona:1883 --group PomonaWRD`" + `
group: PomonaWRD
types:
    - name: Motor
      fields:
        - { name: Speed, type: Double,  arraylen: 0 }
        - { name: Run,   type: Boolean, arraylen: 0 }
nodes:
    - edgenode: W6
      prefix: W6
      onlinetag: W6__Online
      birthtag: W6__LastBirthMs
      rebirthtag: W6__Rebirth
      devices:
        - { device: PLC1, onlinetag: W6_PLC1__Online }
tags:
    - { name: W6_Well_Level,        node: W6, device: "",   metric: Well/Level,    type: Double,  arraylen: 0, writable: false }
    - { name: W6_Pump1,             node: W6, device: "",   metric: Pump1,         type: Motor,   arraylen: 0, writable: false }
    - { name: W6_PLC1_Pump_Run,     node: W6, device: PLC1, metric: Pump/Run,      type: Boolean, arraylen: 0, writable: false }
    - { name: W6_PLC1_Pump_SpeedSP, node: W6, device: PLC1, metric: Pump/SpeedSP,  type: Double,  arraylen: 0, writable: true, init: 0.0 }
`

func mustParse(t *testing.T, src string) Manifest {
	t.Helper()
	m, err := ParseManifest([]byte(src))
	if err != nil {
		t.Fatalf("ParseManifest: %v", err)
	}
	return m
}

func TestParseManifestSample(t *testing.T) {
	m := mustParse(t, sampleManifest)

	if m.Group != "PomonaWRD" {
		t.Errorf("Group = %q, want PomonaWRD", m.Group)
	}
	if len(m.Types) != 1 || m.Types[0].Name != "Motor" {
		t.Fatalf("Types = %+v", m.Types)
	}
	// Field order is template wire order, which is also the ST TYPE member
	// order — it must survive the round trip unsorted.
	if got := []string{m.Types[0].Fields[0].Name, m.Types[0].Fields[1].Name}; got[0] != "Speed" || got[1] != "Run" {
		t.Errorf("Motor fields = %v, want [Speed Run]", got)
	}
	if len(m.Nodes) != 1 {
		t.Fatalf("Nodes = %+v", m.Nodes)
	}
	n := m.Nodes[0]
	if n.EdgeNode != "W6" || n.Prefix != "W6" || n.OnlineTag != "W6__Online" ||
		n.BirthTag != "W6__LastBirthMs" || n.RebirthTag != "W6__Rebirth" {
		t.Errorf("node = %+v", n)
	}
	if len(n.Devices) != 1 || n.Devices[0].Device != "PLC1" || n.Devices[0].OnlineTag != "W6_PLC1__Online" {
		t.Errorf("devices = %+v", n.Devices)
	}
	if len(m.Tags) != 4 {
		t.Fatalf("Tags = %d, want 4", len(m.Tags))
	}
	sp := m.Tags[3]
	if sp.Name != "W6_PLC1_Pump_SpeedSP" || sp.Device != "PLC1" || sp.Metric != "Pump/SpeedSP" || !sp.Writable {
		t.Errorf("SpeedSP binding = %+v", sp)
	}
	if init, ok := sp.Init.(float64); !ok || init != 0 {
		t.Errorf("SpeedSP init = %#v, want float64(0)", sp.Init)
	}
	if m.Tags[0].Writable {
		t.Errorf("Well/Level should not be writable")
	}
	if err := m.Validate(); err != nil {
		t.Fatalf("Validate: %v", err)
	}
}

func TestParseManifestRejectsUnknownKey(t *testing.T) {
	// KnownFields(true): a typo is an error, not a silently dropped binding.
	src := `
nodes:
    - edgenode: W6
tags:
    - { name: W6_X, node: W6, metrik: X, type: Double }
`
	if _, err := ParseManifest([]byte(src)); err == nil {
		t.Fatal("want an error for the misspelled key metrik")
	} else if !strings.Contains(err.Error(), "metrik") {
		t.Errorf("error = %v, want it to name the unknown field", err)
	}
}

func TestParseManifestEmpty(t *testing.T) {
	if _, err := ParseManifest(nil); err == nil {
		t.Fatal("want an error for an empty manifest")
	}
}

func TestLoadManifestReader(t *testing.T) {
	m, err := LoadManifest(strings.NewReader(sampleManifest))
	if err != nil {
		t.Fatalf("LoadManifest: %v", err)
	}
	if m.Group != "PomonaWRD" {
		t.Errorf("Group = %q", m.Group)
	}
}

func TestDatatypeOf(t *testing.T) {
	for name, want := range map[string]spb.DataType{
		"Boolean":  spb.DataType_Boolean,
		"Int32":    spb.DataType_Int32,
		"Double":   spb.DataType_Double,
		"String":   spb.DataType_String,
		"DateTime": spb.DataType_DateTime,
		"Template": spb.DataType_Template,
	} {
		got, ok := datatypeOf(name)
		if !ok || got != want {
			t.Errorf("datatypeOf(%q) = %v,%v want %v,true", name, got, ok, want)
		}
	}
	for _, name := range []string{"Unknown", "Motor", "", "boolean", "DINT"} {
		if _, ok := datatypeOf(name); ok {
			t.Errorf("datatypeOf(%q) = true, want false", name)
		}
	}
}

func TestScalarType(t *testing.T) {
	cases := map[string]ir.TypeKind{
		"Boolean":  ir.TypeBool,
		"Int8":     ir.TypeInt,
		"Int64":    ir.TypeInt,
		"UInt64":   ir.TypeInt,
		"DateTime": ir.TypeInt,
		"Float":    ir.TypeReal,
		"Double":   ir.TypeReal,
		"String":   ir.TypeString,
		"Text":     ir.TypeString,
		"UUID":     ir.TypeString,
	}
	for name, want := range cases {
		got, ok := scalarType(name)
		if !ok {
			t.Errorf("scalarType(%q): not a scalar", name)
			continue
		}
		if got.Kind != want {
			t.Errorf("scalarType(%q).Kind = %v, want %v", name, got.Kind, want)
		}
	}
	for _, name := range []string{"Motor", "DataSet", "Bytes", "Template", "DoubleArray"} {
		if _, ok := scalarType(name); ok {
			t.Errorf("scalarType(%q) = true, want false", name)
		}
	}
}

func TestValidateErrors(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want string
	}{{
		name: "duplicate tag name",
		src: `
nodes: [{edgenode: W6}]
tags:
    - { name: W6_A, node: W6, metric: A, type: Double }
    - { name: W6_A, node: W6, metric: B, type: Double }
`,
		want: `duplicate binding name "W6_A"`,
	}, {
		name: "unknown node",
		src: `
nodes: [{edgenode: W6}]
tags: [{ name: W7_A, node: W7, metric: A, type: Double }]
`,
		want: `unknown node "W7"`,
	}, {
		name: "unknown device",
		src: `
nodes: [{edgenode: W6, devices: [{device: PLC1}]}]
tags: [{ name: W6_X_A, node: W6, device: PLC2, metric: A, type: Double }]
`,
		want: `unknown device "PLC2"`,
	}, {
		name: "unknown type",
		src: `
nodes: [{edgenode: W6}]
tags: [{ name: W6_A, node: W6, metric: A, type: Pump }]
`,
		want: `unknown type "Pump"`,
	}, {
		name: "unrepresentable datatype",
		src: `
nodes: [{edgenode: W6}]
tags: [{ name: W6_A, node: W6, metric: A, type: DataSet }]
`,
		want: "not representable",
	}, {
		name: "reserved rebirth metric",
		src: `
nodes: [{edgenode: W6}]
tags: [{ name: W6_Rebirth, node: W6, metric: Node Control/Rebirth, type: Boolean, writable: true }]
`,
		want: "reserved metric",
	}, {
		name: "companion collides with a binding",
		src: `
nodes: [{edgenode: W6}]
tags: [{ name: W6__Online, node: W6, metric: Online, type: Boolean }]
`,
		want: `which a binding already declares`,
	}, {
		name: "companion collides with another node's",
		src: `
nodes:
    - { edgenode: W6, onlinetag: Site__Online }
    - { edgenode: W7, onlinetag: Site__Online }
`,
		want: `already declares`,
	}, {
		name: "arrays unsupported in a binding",
		src: `
nodes: [{edgenode: W6}]
tags: [{ name: W6_A, node: W6, metric: A, type: Double, arraylen: 4 }]
`,
		want: "arrays unsupported",
	}, {
		name: "arrays unsupported in a type",
		src: `
types: [{name: Motor, fields: [{name: Speeds, type: Double, arraylen: 4}]}]
`,
		want: "arrays unsupported",
	}, {
		name: "duplicate node",
		src: `
nodes: [{edgenode: W6}, {edgenode: W6}]
`,
		want: `declares node "W6" twice`,
	}, {
		name: "duplicate device",
		src: `
nodes: [{edgenode: W6, devices: [{device: PLC1}, {device: PLC1}]}]
`,
		want: `declares device "PLC1" twice`,
	}, {
		name: "one metric bound twice",
		src: `
nodes: [{edgenode: W6}]
tags:
    - { name: W6_A, node: W6, metric: A, type: Double }
    - { name: W6_A2, node: W6, metric: A, type: Double }
`,
		want: "both bind metric W6/A",
	}, {
		name: "binding without a node",
		src: `
tags: [{ name: W6_A, metric: A, type: Double }]
`,
		want: "node is required",
	}, {
		name: "binding without a metric",
		src: `
nodes: [{edgenode: W6}]
tags: [{ name: W6_A, node: W6, type: Double }]
`,
		want: "metric is required",
	}, {
		name: "binding without a type",
		src: `
nodes: [{edgenode: W6}]
tags: [{ name: W6_A, node: W6, metric: A }]
`,
		want: "type is required",
	}, {
		name: "binding without a name",
		src: `
nodes: [{edgenode: W6}]
tags: [{ node: W6, metric: A, type: Double }]
`,
		want: "name is required",
	}, {
		name: "node without an edgenode",
		src:  `nodes: [{prefix: W6}]`,
		want: "edgenode is required",
	}, {
		name: "type shadowing a datatype",
		src:  `types: [{name: Double, fields: [{name: X, type: Double}]}]`,
		want: "shadows the Sparkplug datatype",
	}, {
		name: "duplicate type",
		src: `
types:
    - {name: Motor, fields: [{name: X, type: Double}]}
    - {name: Motor, fields: [{name: Y, type: Double}]}
`,
		want: `declares type "Motor" twice`,
	}, {
		name: "duplicate type field",
		src:  `types: [{name: Motor, fields: [{name: X, type: Double}, {name: X, type: Double}]}]`,
		want: `declares field "X" twice`,
	}}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			m := mustParse(t, tc.src)
			err := m.Validate()
			if err == nil {
				t.Fatalf("Validate() = nil, want an error containing %q", tc.want)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("Validate() = %v, want it to contain %q", err, tc.want)
			}
			if !strings.HasPrefix(err.Error(), "host: ") {
				t.Errorf("error %q should be prefixed host:", err)
			}
		})
	}
}

func TestStructDefsNested(t *testing.T) {
	m := mustParse(t, `
types:
    - name: Motor
      fields:
        - { name: Speed, type: Double }
        - { name: Run,   type: Boolean }
    - name: Skid
      fields:
        - { name: Tag,   type: String }
        - { name: Pump,  type: Motor }
        - { name: Count, type: Int32 }
`)
	defs, err := m.structDefs()
	if err != nil {
		t.Fatalf("structDefs: %v", err)
	}
	if len(defs) != 2 {
		t.Fatalf("defs = %d, want 2", len(defs))
	}
	skid := defs["Skid"]
	if skid == nil {
		t.Fatal("no Skid def")
	}
	wantOrder := []string{"Tag", "Pump", "Count"}
	for i, name := range wantOrder {
		if skid.Fields[i].Name != name {
			t.Errorf("Skid.Fields[%d] = %q, want %q", i, skid.Fields[i].Name, name)
		}
		if skid.FieldIndex[name] != i {
			t.Errorf("Skid.FieldIndex[%q] = %d, want %d", name, skid.FieldIndex[name], i)
		}
	}
	if k := skid.Fields[0].Type.Kind; k != ir.TypeString {
		t.Errorf("Skid.Tag kind = %v, want string", k)
	}
	if k := skid.Fields[2].Type.Kind; k != ir.TypeInt {
		t.Errorf("Skid.Count kind = %v, want int", k)
	}
	pump := skid.Fields[1].Type
	if pump.Kind != ir.TypeStruct || pump.Struct == nil {
		t.Fatalf("Skid.Pump = %+v, want a struct", pump)
	}
	// The nested def must be the *same* def, so a value built for Motor binds
	// to a Skid.Pump field.
	if pump.Struct != defs["Motor"] {
		t.Error("Skid.Pump does not share the memoized Motor def")
	}
	if pump.Struct.Fields[0].Type.Kind != ir.TypeReal {
		t.Errorf("Motor.Speed kind = %v, want real", pump.Struct.Fields[0].Type.Kind)
	}
}

func TestStructDefsErrors(t *testing.T) {
	cases := []struct{ name, src, want string }{{
		name: "cycle",
		src: `
types:
    - {name: A, fields: [{name: b, type: B}]}
    - {name: B, fields: [{name: a, type: A}]}
`,
		want: `type cycle through "A"`,
	}, {
		name: "self cycle",
		src:  `types: [{name: A, fields: [{name: a, type: A}]}]`,
		want: `type cycle through "A"`,
	}, {
		name: "unknown nested type",
		src:  `types: [{name: A, fields: [{name: b, type: Nope}]}]`,
		want: `unknown type "Nope"`,
	}, {
		name: "unrepresentable member datatype",
		src:  `types: [{name: A, fields: [{name: b, type: DataSet}]}]`,
		want: "not representable",
	}, {
		name: "array member",
		src:  `types: [{name: A, fields: [{name: b, type: Double, arraylen: 3}]}]`,
		want: "arrays unsupported",
	}}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			m := mustParse(t, tc.src)
			_, err := m.structDefs()
			if err == nil {
				t.Fatalf("structDefs() = nil error, want %q", tc.want)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("structDefs() = %v, want it to contain %q", err, tc.want)
			}
		})
	}
}

func TestBindingsOrder(t *testing.T) {
	m := mustParse(t, sampleManifest)
	var got []string
	for _, b := range m.Bindings() {
		got = append(got, b.Name)
	}
	want := []string{"W6_PLC1_Pump_Run", "W6_PLC1_Pump_SpeedSP", "W6_Pump1", "W6_Well_Level"}
	if len(got) != len(want) {
		t.Fatalf("Bindings() = %v", got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("Bindings() = %v, want %v", got, want)
		}
	}
	// Bindings must not alias the manifest's own slice.
	m.Bindings()[0].Name = "mutated"
	if m.Tags[0].Name != "W6_Well_Level" {
		t.Error("Bindings() aliases Manifest.Tags")
	}
}

func TestBindingType(t *testing.T) {
	m := mustParse(t, sampleManifest)
	defs, err := m.structDefs()
	if err != nil {
		t.Fatalf("structDefs: %v", err)
	}
	scalar, err := bindingType(Binding{Name: "x", Type: "Double"}, defs)
	if err != nil || scalar.Kind != ir.TypeReal {
		t.Errorf("bindingType(Double) = %+v, %v", scalar, err)
	}
	tmpl, err := bindingType(Binding{Name: "y", Type: "Motor"}, defs)
	if err != nil {
		t.Fatalf("bindingType(Motor): %v", err)
	}
	if tmpl.Kind != ir.TypeStruct || tmpl.Struct != defs["Motor"] {
		t.Errorf("bindingType(Motor) = %+v", tmpl)
	}
	if _, err := bindingType(Binding{Name: "z", Type: "Nope"}, defs); err == nil {
		t.Error("bindingType(Nope) = nil error")
	}
}
