// types.go holds every type shared across this package: the driver's own
// struct, its configuration, the manifest shapes, the per-node state machine
// records, and the status shapes /api/drivers renders.
//
// OWNED BY B1/B2/B3 JOINTLY: implement your methods in your own file
// (manifest.go + mapping.go / state.go / mqtt.go + status.go). Do NOT edit
// types.go without coordinating — a field added here is fine, a field renamed
// or removed here breaks the other two agents' in-flight work.
//
// Field comments name the file that owns each group. "Owned by" means "that
// file's code writes it"; anyone may read.

package host

import (
	"context"
	"log/slog"
	"sync"
	"time"

	nio "github.com/joyautomation/nautilus/io"
	"github.com/joyautomation/nautilus/lang/ir"
	"github.com/joyautomation/nautilus/sparkplug"
)

// ── Configuration ────────────────────────────────────────────────────────

// Config is the host application's connection and behaviour configuration.
// Copied verbatim from docs/design/sparkplug-host.md §1.
type Config struct {
	BrokerURL          string   // tcp://host:1883, ssl://host:8883
	HostID             string   // STATE topic spBv1.0/STATE/<HostID>
	GroupIDs           []string // groups to consume; empty = "+" (all)
	ClientID           string   // default "nautilus-host-" + HostID
	Username, Password string
	Keepalive          time.Duration // default 30s
	Primary            bool          // publish STATE. false = passive consumer
	StateForm          string        // "3.0" (default) | "2.x" | "both"
	ReorderTimeout     time.Duration // default 5s: unfilled seq gap → NCMD Rebirth
	StaleAfter         time.Duration // 0 = off; silence this long → node stale
	RebirthOnStart     bool          // ask every manifest node to rebirth at connect (default true)
	CommandInterval    time.Duration // coalesce window for outbound NCMD/DCMD (default 100ms)
	Log                *slog.Logger

	// ADDED BY B3 (mqtt.go).

	// NoRebirthOnStart is the explicit opt-out from RebirthOnStart, which
	// defaults to *true*: a plain Config literal leaves RebirthOnStart false,
	// so New cannot tell "unset" from "off" without a second field. New reads
	// the pair as: RebirthOnStart || !NoRebirthOnStart.
	NoRebirthOnStart bool

	// Leader reports whether this replica currently holds leadership. It gates
	// the STATE birth/death publish and every outbound NCMD/DCMD, so a standby
	// under `redundancy:` never publishes STATE online — its LWT would
	// otherwise flap store-and-forward across every site
	// (docs/design/sparkplug-host.md §8.1). nil means "always the leader".
	//
	// The driver samples it once per connection attempt (the will is baked
	// into CONNECT and cannot be changed mid-session) and once a second while
	// connected; a change forces a reconnect so the will matches reality.
	Leader func() bool
}

// Discovery modes for metrics seen on the wire but absent from the manifest
// (WithDiscovery / the manifest tier's on-unknown key).
const (
	DiscoveryLog    = "log"    // default: log once each at INFO, count, expose via Discovered()
	DiscoveryIgnore = "ignore" // count only
	DiscoveryStrict = "strict" // WARN and report the driver as degraded
)

// RebirthMetric is the reserved Sparkplug metric name for a rebirth command.
// A manifest binding that targets it is rejected in New; <site>__Rebirth is
// the sanctioned operator path.
const RebirthMetric = "Node Control/Rebirth"

// ── Manifest (B1) ────────────────────────────────────────────────────────
//
// Decoded with yaml.v3 KnownFields(true) and NO yaml struct tags, matching
// eip.Manifest's convention exactly: keys are the lowercased Go field names
// ("edgenode", "onlinetag", "arraylen"). Changing a field name changes the
// on-disk key and every generated manifest — coordinate.

// Manifest is the committed description of what this project consumes from
// one Sparkplug group: the template shapes it depends on, the edge nodes it
// expects, and the tag bindings. Generated by `nautilus sparkplug import`;
// births are validated against it at runtime so drift fails loudly.
type Manifest struct {
	// Group is the Sparkplug group_id these nodes live under.
	Group string
	// Types are the Template (UDT) definitions bound tags reference.
	Types []TypeDef
	// Nodes are the edge nodes to consume, with their synthesized
	// quality-companion tag names.
	Nodes []Node
	// Tags are the metric-to-nautilus-tag bindings.
	Tags []Binding
}

// TypeDef mirrors one Sparkplug Template definition. Fields appear in
// template member order, which is also the ir.StructDef field order and the
// generated ST TYPE member order.
type TypeDef struct {
	Name   string
	Fields []FieldDef
}

// FieldDef is one template member: Type is a Sparkplug datatype name
// ("Boolean", "Int32", "Double", "String", ...) or another TypeDef name.
// ArrayLen > 0 marks a fixed array member.
type FieldDef struct {
	Name     string
	Type     string
	ArrayLen int
}

// Node is one edge node in the group. The synthesized companion tags are
// declared here so ST can interlock on them and the HMI can bind them; the
// double underscore is reserved (the sanitizer collapses "_" runs, so no real
// metric name can produce it).
type Node struct {
	// EdgeNode is the Sparkplug edge_node_id, verbatim.
	EdgeNode string
	// Prefix is the tag-name prefix for this node's metrics; empty means
	// sanitize(EdgeNode).
	Prefix string
	// OnlineTag is a BOOL input tag: node online (NBIRTH seen, no matching
	// NDEATH). Empty means don't synthesize it.
	OnlineTag string
	// BirthTag is an INT input tag carrying the last NBIRTH epoch ms.
	BirthTag string
	// RebirthTag is a BOOL *output* tag: a rising edge sends NCMD Rebirth.
	RebirthTag string
	// Devices are the Sparkplug devices under this node.
	Devices []Device
}

// Device is one Sparkplug device under an edge node.
type Device struct {
	// Device is the Sparkplug device_id, verbatim.
	Device string
	// OnlineTag is a BOOL input tag: device online.
	OnlineTag string
}

// Binding maps one Sparkplug metric to one nautilus tag.
type Binding struct {
	// Name is the nautilus tag (what ST declares under VAR_EXTERNAL and Go
	// reads from the tag store).
	Name string
	// Node is the edge_node_id this metric belongs to.
	Node string
	// Device is the device_id, or "" for a node-level metric (NDATA).
	Device string
	// Metric is the verbatim Sparkplug metric name.
	Metric string
	// Member is a dotted path to ONE member inside a Template metric
	// ("START", "LVL.CTL1HSP"), or "" for the metric as a whole.
	//
	// A member binding is how an operator commands one control of a site's
	// UDT without touching its siblings. It is a SCALAR nautilus tag carrying
	// the leaf member's type, and it is OUTPUT-ONLY: Writable must be true.
	// Reads still come from the metric's own struct binding — duplicating
	// every member as an input tag would double the fleet's tag count for no
	// gain, and the struct tag already carries every member's live value.
	//
	// A write publishes an NCMD/DCMD carrying a PARTIAL template — the parent
	// metric's name, with only this member inside it — which Sparkplug B
	// permits and nautilus's own edge (sparkplug/command.go) merges member by
	// member.
	//
	// Member requires Type to name a types: entry, and the path must resolve
	// to a scalar leaf in it.
	Member string
	// Type is a Sparkplug datatype name or a TypeDef name.
	Type string
	// ArrayLen > 0 marks an array metric.
	ArrayLen int
	// Writable includes the tag in the output set: writes to the nautilus tag
	// go out as NCMD (Device == "") or DCMD.
	Writable bool
	// Init is the generated output tag's initial value, so the tag exists
	// from scan one. Nil means the type zero.
	Init any
	// Desc is a human description of what this metric IS ("Well 6 raw span
	// minimum"), carried from the --sites file's `desc:` into the generated
	// tag file's `desc:`. It is what an alarm name's {desc} renders instead
	// of the sanitized tag name, and what an HMI can label a control with.
	// Empty when the source did not say — never invented.
	Desc string
}

// ── Driver ───────────────────────────────────────────────────────────────

// Driver consumes a Sparkplug group and implements io.Driver. It owns a
// background connection loop: connect → subscribe → publish STATE birth →
// request rebirths → consume, reconnecting with capped backoff. ReadInputs
// never blocks on the network; it returns the latest snapshot, offline nodes
// included. WriteOutputs enqueues changed values; a writer goroutine coalesces
// them into NCMD/DCMD payloads on a CommandInterval tick.
type Driver struct {
	// ── configuration, set in New, read-only afterwards ──
	cfg       Config
	manifest  Manifest
	log       *slog.Logger
	discovery string // DiscoveryLog | DiscoveryIgnore | DiscoveryStrict

	// ── manifest-derived indexes (owned by B1: manifest.go, mapping.go) ──
	// Built once in New; read-only afterwards, so no lock.

	// defs is the manifest type name → ir.StructDef, memoized and
	// cycle-checked. Handed to the runtime through StructDefs().
	defs map[string]*ir.StructDef
	// inputs are the non-writable bindings, in InputNames() order.
	inputs []Binding
	// byName indexes writable bindings by nautilus tag name.
	byName map[string]Binding
	// byMetric routes an inbound metric to its binding, keyed by
	// (edge node, device, metric name). Member bindings are NOT in it: they
	// are output-only, so nothing inbound ever routes to one.
	byMetric map[metricKey]Binding
	// members is the precomputed write plan for every member binding, keyed
	// by nautilus tag name — resolved once here so flushWrites never walks
	// the types: block.
	members map[string]memberOut
	// memberOf is members read the other way round: the parent metric → the
	// member OUTPUT tags that address a leaf inside it. It is what lets
	// an inbound template value adopt itself as those outputs' baseline
	// (adoptMembersLocked), so the host never commands a member back to the
	// zero of its type.
	memberOf map[metricKey][]string
	// nodeCfg indexes manifest nodes by edge_node_id.
	nodeCfg map[string]Node

	// ── ADDED BY B3 (driver.go, mqtt.go); built in New, read-only after ──

	// groups is the resolved subscription group list: Config.GroupIDs if set,
	// else the manifest's Group, else the "+" wildcard.
	groups []string
	// rebirthTags maps a manifest node's RebirthTag (a BOOL *output*) to its
	// edge_node_id. A rising edge on one of these sends NCMD Rebirth; they are
	// synthesized, so they are not in byName.
	rebirthTags map[string]string
	// synthInputs are the driver-synthesized companion INPUT tag names —
	// Node.OnlineTagName / BirthTagName per node and DeviceOnlineTagName per
	// device — sorted. They are not bindings (no metric backs them), so they
	// live beside inputs rather than in it. (added by B1)
	synthInputs []string
	// synthOutputs are the synthesized companion OUTPUT tag names:
	// Node.RebirthTagName, one per node, sorted. (added by B1)
	synthOutputs []string
	// (rebirthTags — declared above in the B3 block; B1 fills it in
	// buildIndexes, B3 reads it in WriteOutputs.)

	// ── state machine (owned by B2: state.go) ──
	// mu guards everything in this block.
	mu sync.Mutex
	// started flips true once Start has run; before that ReadInputs errors
	// like eip ("host: not connected yet").
	started bool
	// nodes is the per-edge-node state, keyed by nodeKey.
	nodes map[nodeKey]*nodeState
	// values is the snapshot ReadInputs returns: nautilus tag name → value.
	// Values survive death — Sparkplug's last value *is* the value.
	values nio.Values
	// unknown counts metrics seen but not bound, keyed by their manifest
	// line, for Discovered() and /api/drivers extra.unknown.
	unknown map[metricKey]*discovery
	stats   stats

	// ── added by B2 (state.go); still guarded by mu ──
	//
	// The state machine asks for an NCMD Node Control/Rebirth through B3's
	// onRebirthNeeded hook (declared below, with the outbound machinery it
	// belongs to): an unfilled sequence gap, data from a node that has not
	// birthed, or a node gone stale. It is always called with mu released.

	// rebirthQ accumulates rebirth requests raised while mu is held;
	// flushRebirths drains it and invokes onRebirthNeeded outside the lock.
	rebirthQ []nodeKey
	// adoptQ accumulates member-output baseline adoptions raised while mu is
	// held. It exists for the same reason rebirthQ does — the write maps are
	// under wmu, and flushWrites already takes wmu before d.mu (nodeOnline),
	// so taking wmu under d.mu would invert the order. flushAdopts drains it
	// with neither lock held and then takes wmu alone.
	adoptQ []adoption
	// degraded is set when the discovery policy is DiscoveryStrict and an
	// unmanifested metric has been seen. /api/drivers reports "degraded".
	degraded bool
	// warned dedupes the log-once diagnostics the state machine emits
	// (unresolvable aliases, unknown template members, unsupported
	// bindings), keyed by an opaque reason string.
	warned map[string]bool

	// ── outbound commands (owned by B3: mqtt.go) ──
	// OUTPUTS ARE COMMANDS. The runtime hands WriteOutputs *all* outputs
	// every scan, so "the driver was handed a value" is not "the operator
	// asked for it". Three maps keep those apart, all guarded by wmu and all
	// holding CANONICAL values (canonWrite: an ir.Value, coerced to the
	// template leaf's type for a member output) so comparisons never trip
	// over int64-vs-float64 or a plain-vs-ir shape.
	wmu sync.Mutex
	// pending are queued commands: nautilus tag name → desired value.
	pending map[string]any
	// lastOut is the CHANGE DETECTOR: the last value the runtime handed us
	// for this output that we have accounted for. A scan whose value equals
	// lastOut is not a command and produces nothing on the wire. The very
	// first snapshot after Start (and after each reconnect) fills lastOut
	// without publishing — see armBaseline.
	lastOut map[string]any
	// remote is what we believe the NODE currently holds: the last value we
	// published for this tag, or — for a member output — the member's live
	// value adopted from an NBIRTH/DBIRTH/NDATA (adoptMembersLocked). A
	// command whose value the node already holds is suppressed.
	remote map[string]any
	// baseline arms the next WriteOutputs snapshot as a baseline: recorded
	// into lastOut, never published.
	baseline bool
	wkick    chan struct{} // non-blocking nudge to the writer goroutine

	// rebirths is the async NCMD-Rebirth queue. state.go's reorder timer runs
	// under d.mu and inside paho's ordered message goroutine, so it must never
	// publish inline; it calls onRebirthNeeded, which does a non-blocking send
	// here and lets the writer goroutine do the I/O. Full queue = dropped
	// request; the next gap re-raises it. ADDED BY B3.
	rebirths chan nodeKey
	// onRebirthNeeded is the state machine's escape hatch: an unfilled seq gap
	// (ReorderTimeout) asks for a rebirth. Set in New (B3), called from
	// state.go (B2). Never blocks, never takes d.mu.
	onRebirthNeeded func(group, edge string)

	// ── transport (owned by B3: mqtt.go) ──
	// pub is the publish seam; nil until connected. Tests substitute a fake,
	// which is what makes the whole state machine testable without a broker.
	pub       publisher
	connected bool
	lastErr   error
	// sessionTS is the will/birth timestamp captured once per connection
	// attempt before CONNECT. The STATE birth must carry the byte-identical
	// value the will carries (TCK host-topic-phid-birth-payload-timestamp).
	sessionTS int64
	cancel    context.CancelFunc
	done      chan struct{}
}

// stats are the monotonic counters Status() reports.
type stats struct {
	Msgs       uint64
	Rebirths   uint64
	SeqGaps    uint64
	WriteDrops uint64
}

// ── Internal seam ────────────────────────────────────────────────────────

// publisher is the driver's only outbound dependency. Everything above it —
// the state machine, the command writer, STATE birth/death — is expressed in
// terms of topics and bytes, so unit tests drive the whole driver with a fake
// publisher and no broker. mqtt.go supplies the paho-backed implementation.
type publisher interface {
	publish(topic string, qos byte, retain bool, payload []byte) error
}

// The inbound half of the seam is (*Driver).handleMessage(topic string,
// payload []byte) — a pure function of topic and bytes with no MQTT types in
// sight, so a test feeds births, data and deaths as sparkplug.Payload{...}
// .Encode() byte slices. It lives in state.go (B2); mqtt.go's paho message
// handler does nothing but call it.

// ── Per-node state (B2) ──────────────────────────────────────────────────

// nodeKey identifies one edge node across groups.
type nodeKey struct {
	Group, EdgeNode string
}

// metricKey identifies one metric within a group: Device is "" for a
// node-level metric.
type metricKey struct {
	EdgeNode, Device, Metric string
}

// bindKey identifies what one binding CLAIMS: a metric, or one member path
// inside it. A struct binding and any number of member bindings can share a
// metric; two bindings claiming the same member path cannot.
type bindKey struct {
	metricKey
	Member string
}

// memberOut is one member binding's write plan, resolved from the types:
// block in buildIndexes so the write path is a lookup rather than a walk.
type memberOut struct {
	// path is the dotted member path split into segments; the last is the
	// leaf member's own name.
	path []string
	// refs is the TemplateRef at each level of the nesting: refs[0] is the
	// metric's own type, refs[i] the type path[i-1] steps into. len(refs) ==
	// len(path).
	refs []string
	// leaf is the leaf member's ir.Type, so a write is coerced to what the
	// template declares before it goes on the wire.
	leaf *ir.Type
	// datatype is the leaf's Sparkplug datatype NAME ("Double", "Boolean"),
	// which the generated tag file's init: follows.
	datatype string
}

// adoption is one member output's baseline, taken from the live value the
// node just reported for the member: "the site already holds this, so a
// command carrying it would be a no-op". Queued under d.mu, applied to
// Driver.remote under wmu by flushAdopts.
type adoption struct {
	name  string
	value any
}

// metricRef is what an alias resolves to inside one edge node. Aliases are
// unique within an edge node *including its devices* (spec), so one table per
// node serves the node and all its devices.
type metricRef struct {
	Device string // "" = node-level
	Metric string
}

// nodeState is one edge node's live state. Guarded by Driver.mu.
type nodeState struct {
	group, edge string
	online      bool
	// bdSeq from the NBIRTH. An NDEATH whose bdSeq does not match is a late
	// will from a prior session and must be ignored.
	bdSeq int64
	// seq is the last accepted sequence number; seqPrimed is false until the
	// NBIRTH (seq MUST be 0) establishes it.
	seq       uint64
	seqPrimed bool
	birthMs   int64
	lastMs    int64
	// aliases is the ONE alias table per edge node, shared with its devices.
	aliases map[uint64]metricRef
	devices map[string]*deviceState
	// tmpl holds the NBIRTH Template definitions by type name, and defs the
	// ir.StructDefs built from them.
	tmpl map[string]*sparkplug.Template
	defs map[string]*ir.StructDef
	// gapTimer fires ReorderTimeout after an unfilled seq gap → NCMD Rebirth.
	gapTimer *time.Timer
	// gapGen (B2) invalidates an in-flight gapTimer callback: stopGap bumps
	// it, and the callback bails when the generation it captured is stale.
	// time.Timer.Stop cannot report whether an AfterFunc already started.
	gapGen uint64
	// pending is the out-of-order buffer, keyed by seq.
	pending map[uint64]queued
	// rebirthAsked (B2) debounces rebirth requests to one per birth cycle:
	// set when the state machine asks, cleared by the next NBIRTH.
	rebirthAsked bool
	// metrics counts the node-level metrics the last birth carried.
	metrics int
	// stale marks a node silent for longer than StaleAfter.
	stale bool
}

// deviceState is one Sparkplug device under an edge node.
type deviceState struct {
	id      string
	online  bool
	birthMs int64
	metrics int
}

// queued is one buffered out-of-order message awaiting its predecessor.
type queued struct {
	kind    string // "NDATA" | "DDATA" | "DBIRTH" | "DDEATH"
	device  string // "" for node-level messages
	payload sparkplug.Payload
	at      time.Time
}

// discovery is one unmanifested metric, counted and rendered as the exact
// YAML line to add.
type discovery struct {
	key      metricKey
	datatype string
	count    int
	logged   bool
}

// ── Status (read by internal/project/drivers.go) ─────────────────────────

// Status is the driver's health snapshot, adapted into a server.DriverStatus
// for /api/drivers. Copied from docs/design/sparkplug-host.md §1.
type Status struct {
	Broker, HostID                      string
	Groups                              []string
	Connected                           bool
	StateOnlineMs                       int64
	Msgs, Rebirths, SeqGaps, WriteDrops uint64
	Unknown                             int
	// Degraded is set when the discovery policy is DiscoveryStrict and an
	// unmanifested metric has been seen — /api/drivers reports the driver
	// "degraded" for it (docs/design/sparkplug-host.md §5).
	Degraded  bool
	LastError string
	Nodes     []NodeStatus
}

// NodeStatus is one edge node's row.
type NodeStatus struct {
	Group, EdgeNode    string
	Online, Stale      bool
	BdSeq              int64
	Seq                uint64
	BirthMs, LastMsgMs int64
	Metrics            int
	Devices            []DeviceStatus
}

// DeviceStatus is one device sub-row, flattened as "<edge>/<device>" in the
// /api/drivers device list.
type DeviceStatus struct {
	ID      string
	Online  bool
	BirthMs int64
	Metrics int
}

// Discovered is one metric seen on the wire but absent from the manifest.
// YAML is the exact manifest line to add, so the remedy is copy-paste (or
// re-run the import).
type Discovered struct {
	Group, EdgeNode, Device, Metric string
	Datatype                        string
	Count                           int
	YAML                            string
}
