// generate.go dispatches to a profile (only "node" so far) and renders its
// result to bytes: prometheus_manifest.yaml by hand (modbus/codegen's
// convention — deterministic, reviewable, and pinned by a round-trip test)
// and tags/prometheus.yaml via internal/tagfile, the shared renderer every
// generator uses.
package codegen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/joyautomation/nautilus/hw"
	"github.com/joyautomation/nautilus/internal/tagfile"
	"github.com/joyautomation/nautilus/prom"
)

// Options steers one generation.
type Options struct {
	// Tag is the source id AND the tag prefix every generated struct tag is
	// named from ("NODE1" → "NODE1", "NODE1_Fan1", "NODE1_Temp_CPU_Core_0").
	Tag string
	// URL is the scrape URL recorded into the manifest's one source.
	URL string
	// Profile selects the metric-to-member mapping; "" means "node" (the
	// only one this package ships).
	Profile string
}

// Output is one generation's result.
type Output struct {
	Manifest prom.Manifest
	// Desc is tag name → one-line description, for the tag file; codegen's
	// own bookkeeping, not carried by prom.Manifest itself.
	Desc map[string]string
}

// Generate builds the manifest (and its tag-file metadata) from one parsed
// scrape. Deterministic: same scrape in, same Output out, regardless of
// scrape.Samples' order (every enumeration here sorts before it renders).
func Generate(scrape prom.Scrape, opts Options) (Output, error) {
	if opts.Tag == "" {
		return Output{}, fmt.Errorf("codegen: --tag is required")
	}
	if opts.URL == "" {
		return Output{}, fmt.Errorf("codegen: --url is required")
	}
	profile := opts.Profile
	if profile == "" {
		profile = "node"
	}
	switch profile {
	case "node":
		return generateNode(scrape, opts)
	}
	return Output{}, fmt.Errorf("codegen: unknown profile %q (have: node)", profile)
}

// ── manifest rendering ───────────────────────────────────────────────────

// ManifestYAML renders the manifest by hand, matching prom.LoadManifest's
// decode shape exactly (round-tripped by codegen_test.go): sources as block
// maps with defaulted keys omitted, one flow map per member under a block
// `members:` — the shape docs/design/it-drivers.md §6.1 shows.
func ManifestYAML(m prom.Manifest, command string) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `%s` — the\n", command)
	b.WriteString("# \"node\" profile's bindings against that scrape. Do not edit — re-run the\n")
	b.WriteString("# import. Validated offline: `naut check` builds the driver from this file\n")
	b.WriteString("# with no exporter in sight.\n")

	b.WriteString("sources:\n")
	sources := append([]prom.Source(nil), m.Sources...)
	sort.Slice(sources, func(i, j int) bool { return sources[i].ID < sources[j].ID })
	for _, s := range sources {
		fmt.Fprintf(&b, "  - id: %s\n", s.ID)
		fmt.Fprintf(&b, "    url: %s\n", s.URL)
		if s.Timeout != 0 {
			fmt.Fprintf(&b, "    timeout: %s\n", s.Timeout)
		}
		if s.Interval != 0 {
			fmt.Fprintf(&b, "    interval: %s\n", s.Interval)
		}
		if s.StaleAfter != 0 {
			fmt.Fprintf(&b, "    staleafter: %s\n", s.StaleAfter)
		}
		if s.Enable != "" {
			fmt.Fprintf(&b, "    enable: %s\n", s.Enable)
		}
		if s.BearerEnv != "" {
			fmt.Fprintf(&b, "    bearerenv: %s\n", s.BearerEnv)
		}
		if s.BearerFile != "" {
			fmt.Fprintf(&b, "    bearerfile: %s\n", s.BearerFile)
		}
		if s.BasicEnv != "" {
			fmt.Fprintf(&b, "    basicenv: %s\n", s.BasicEnv)
		}
		if s.BasicFile != "" {
			fmt.Fprintf(&b, "    basicfile: %s\n", s.BasicFile)
		}
		if s.InsecureSkipVerify {
			b.WriteString("    insecureskipverify: true\n")
		}
	}

	b.WriteString("tags:\n")
	tags := append([]prom.Tag(nil), m.Tags...)
	sort.Slice(tags, func(i, j int) bool { return tags[i].Name < tags[j].Name })
	for _, t := range tags {
		fmt.Fprintf(&b, "  - name: %s\n", t.Name)
		fmt.Fprintf(&b, "    type: %s\n", t.Type)
		fmt.Fprintf(&b, "    source: %s\n", t.Source)
		b.WriteString("    members:\n")
		members := make([]string, 0, len(t.Members))
		for name := range t.Members {
			members = append(members, name)
		}
		sort.Strings(members)
		width := 0
		for _, name := range members {
			if len(name) > width {
				width = len(name)
			}
		}
		for _, name := range members {
			fmt.Fprintf(&b, "      %-*s %s\n", width+1, name+":", renderBinding(t.Members[name]))
		}
	}

	if len(m.Writes) > 0 {
		b.WriteString("writes:\n")
		writes := append([]hw.WriteDecl(nil), m.Writes...)
		sort.Slice(writes, func(i, j int) bool { return writes[i].Name < writes[j].Name })
		for _, w := range writes {
			fmt.Fprintf(&b, "  - {name: %s, tag: %s, member: %s}\n", w.Name, w.Tag, w.Member)
		}
	}
	return []byte(b.String())
}

// renderBinding renders one member's binding as a flow map, keys in one
// fixed canonical order, empty/zero fields omitted.
func renderBinding(b prom.Binding) string {
	var parts []string
	hwb := b.Binding
	if hwb.Const != nil {
		parts = append(parts, "const: "+yamlScalar(hwb.Const))
	}
	if hwb.Derived != "" {
		parts = append(parts, "derived: "+yamlString(hwb.Derived))
	}
	if b.Metric != "" {
		parts = append(parts, "metric: "+b.Metric)
	}
	if len(b.Labels) > 0 {
		parts = append(parts, "labels: "+renderStringMap(b.Labels))
	}
	if b.Agg != "" {
		parts = append(parts, "agg: "+b.Agg)
	}
	if b.Label != "" {
		parts = append(parts, "label: "+b.Label)
	}
	if b.Expr != "" {
		parts = append(parts, "expr: "+yamlString(b.Expr))
	}
	if len(b.From) > 0 {
		parts = append(parts, "from: "+renderFrom(b.From))
	}
	if len(hwb.Map) > 0 {
		parts = append(parts, "map: "+renderAnyMap(hwb.Map))
	}
	if hwb.Eq != nil {
		parts = append(parts, "eq: "+yamlScalar(hwb.Eq))
	}
	if hwb.Scale != 0 {
		parts = append(parts, "scale: "+floatYAML(hwb.Scale))
	}
	if hwb.Offset != 0 {
		parts = append(parts, "offset: "+floatYAML(hwb.Offset))
	}
	if hwb.Rate {
		parts = append(parts, "rate: true")
	}
	if hwb.Width != 0 {
		parts = append(parts, fmt.Sprintf("width: %d", hwb.Width))
	}
	if hwb.ScanClass != "" {
		parts = append(parts, "scan-class: "+hwb.ScanClass)
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func renderFrom(sels map[string]prom.Selector) string {
	names := make([]string, 0, len(sels))
	for n := range sels {
		names = append(names, n)
	}
	sort.Strings(names)
	parts := make([]string, len(names))
	for i, n := range names {
		parts[i] = n + ": " + renderSelector(sels[n])
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func renderSelector(s prom.Selector) string {
	var parts []string
	parts = append(parts, "metric: "+s.Metric)
	if len(s.Labels) > 0 {
		parts = append(parts, "labels: "+renderStringMap(s.Labels))
	}
	if s.Agg != "" {
		parts = append(parts, "agg: "+s.Agg)
	}
	if s.Rate {
		parts = append(parts, "rate: true")
	}
	if s.Label != "" {
		parts = append(parts, "label: "+s.Label)
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func renderStringMap(m map[string]string) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = k + ": " + yamlString(m[k])
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func renderAnyMap(m map[string]any) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = k + ": " + yamlScalar(m[k])
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

// yamlScalar renders a manifest literal (a const: or eq: value) the way it
// decodes back: bools and numbers bare, strings quoted.
func yamlScalar(v any) string {
	switch x := v.(type) {
	case bool:
		return strconv.FormatBool(x)
	case string:
		return yamlString(x)
	case int:
		return strconv.Itoa(x)
	case int64:
		return strconv.FormatInt(x, 10)
	case float64:
		return floatYAML(x)
	}
	return yamlString(fmt.Sprint(v))
}

func yamlString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`)
	return `"` + r.Replace(s) + `"`
}

func floatYAML(v float64) string { return strconv.FormatFloat(v, 'g', -1, 64) }

// ── tag file ─────────────────────────────────────────────────────────────

// TagsYAML renders the tag file: role input, type the struct's contract
// type, desc from Output.Desc.
func TagsYAML(out Output) ([]byte, error) {
	header := []string{
		"Generated by `naut prometheus import`. Do not edit — re-run the import,",
		"or `naut prometheus tags <manifest>` to re-derive this file from an",
		"already-committed manifest.",
		"",
		"Compose it into a project with:  tag-files: [tags/prometheus.yaml]",
	}
	var tags []tagfile.Tag
	for _, t := range out.Manifest.Tags {
		tags = append(tags, tagfile.Tag{Name: t.Name, Role: "input", Type: t.Type, Desc: out.Desc[t.Name]})
	}
	// The driver-synthesised companions, declared so a program can read
	// them — a host's values hold (Stale) when the exporter stops
	// answering, so interlock on __Online (the snmp/redfish rule).
	for _, s := range out.Manifest.Sources {
		tags = append(tags,
			tagfile.Tag{Name: hw.OnlineTagName(s.ID), Role: "input", Desc: "exporter " + s.ID + " answered within stale-after — interlock on this (driver-synthesised)"},
			tagfile.Tag{Name: hw.LastPollTagName(s.ID), Role: "input", Unit: "ms", Desc: "epoch ms of " + s.ID + "'s last complete scrape, 0 before the first (driver-synthesised)"})
	}
	return tagfile.Render(header, tags)
}
