package project

// The manifest tier's alarm contract: rules expand against the COMPOSED
// tag set (so a generated tag file's tags are claimable), a duplicate id
// across two sources is an error naming both, and a condition path that
// names a member the type does not have is caught offline — by `nautilus
// check`, on a laptop, not by an alarm sitting Suppressed forever on a
// commissioning day.

import (
	"strings"
	"testing"
	"testing/fstest"
	"time"

	"github.com/joyautomation/nautilus/runtime"
)

const alarmLib = `TYPE
  AnalogInput : STRUCT
    PV : REAL;
    HH : BOOL;
    L  : BOOL;
  END_STRUCT;
END_TYPE
`

const alarmProgram = `PROGRAM Main
VAR_EXTERNAL
    RTU9_WEL15_FIT_001 : AnalogInput;
    RTU9__Online : BOOL;
    Duty : REAL;
END_VAR
RTU9_WEL15_FIT_001.HH := RTU9_WEL15_FIT_001.PV > 100.0;
RTU9_WEL15_FIT_001.L  := RTU9_WEL15_FIT_001.PV < 10.0;
Duty := RTU9_WEL15_FIT_001.PV;
END_PROGRAM`

// alarmFS is a two-tag project: one struct tag whose members a rule can
// claim, one flat BOOL, and the online flag a rule's `enable:` template
// resolves to.
func alarmFS(manifest string, extra map[string]string) fstest.MapFS {
	fsys := fstest.MapFS{
		"nautilus.yaml": &fstest.MapFile{Data: []byte(manifest)},
		"blocks.st":     &fstest.MapFile{Data: []byte(alarmLib)},
		"program.st":    &fstest.MapFile{Data: []byte(alarmProgram)},
	}
	for name, body := range extra {
		fsys[name] = &fstest.MapFile{Data: []byte(body)}
	}
	return fsys
}

const alarmTags = `
tasks:
  - program: program.st
tags:
  - { name: RTU9_WEL15_FIT_001, role: state, type: AnalogInput, init: { PV: 50.0 }, desc: "Well 15 flow" }
  - { name: RTU9_WEL15_INT_001_YA, role: state, init: false, desc: "Well 15 intrusion" }
  - { name: RTU9__Online, role: setpoint, init: true }
  - { name: Duty, role: state, init: 0.0 }
`

// load builds the project and a runtime for it — a rule matches a struct
// TYPE, so nothing about alarms is knowable before the TYPE table compiles.
func loadAlarms(t *testing.T, fsys fstest.MapFS) (*Project, *runtime.Runtime) {
	t.Helper()
	proj, err := Load(fsys, "")
	if err != nil {
		t.Fatal(err)
	}
	rt, err := runtime.New(proj.Runtime)
	if err != nil {
		t.Fatal(err)
	}
	return proj, rt
}

// The headline claim: a rule names a (type, member) pair once and every
// matching tag gets an instance, with names, sites and enable tags
// interpolated from the tag it landed on.
func TestRulesExpandAgainstComposedTags(t *testing.T) {
	proj, rt := loadAlarms(t, alarmFS(alarmTags+`
alarms:
  site-from: "^([A-Za-z]+[0-9]+)_"
  area-from: "^[A-Za-z]+[0-9]+_([A-Za-z]+[0-9]+)_"
  rules:
    - match: { type: AnalogInput, member: HH }
      name: "{desc} High High"
      priority: high
      on-delay: 5m
      enable: "{site}__Online"
  defs:
    - { id: intrusion, tag: RTU9_WEL15_INT_001_YA, name: Intrusion, priority: critical }
`, nil))

	defs, err := proj.AlarmDefs(rt)
	if err != nil {
		t.Fatal(err)
	}
	if len(defs) != 2 {
		t.Fatalf("got %d definitions, want 2: %+v", len(defs), defs)
	}
	// Sorted by id: "RTU9_WEL15_FIT_001.HH" then "intrusion".
	d := defs[0]
	if d.ID != "RTU9_WEL15_FIT_001.HH" {
		t.Errorf("id = %q, want the default {path}", d.ID)
	}
	if d.Name != "Well 15 flow High High" {
		t.Errorf("name = %q — the {desc} template did not interpolate the tag's own description", d.Name)
	}
	if d.Site != "RTU9" || d.Area != "WEL15" {
		t.Errorf("site/area = %q/%q, want RTU9/WEL15 from site-from/area-from", d.Site, d.Area)
	}
	if d.Enable != "RTU9__Online" {
		t.Errorf("enable = %q, want the {site} template resolved", d.Enable)
	}
	if d.OnDelay != 5*time.Minute {
		t.Errorf("on-delay = %s, want 5m", d.OnDelay)
	}
	if defs[1].ID != "intrusion" || defs[1].Priority.String() != "critical" {
		t.Errorf("the explicit definition came through as %+v", defs[1])
	}

	// A member no rule claims produces no definition — first match wins,
	// and nothing matches L here.
	for _, d := range defs {
		if strings.HasSuffix(d.Tag, ".L") {
			t.Errorf("%s was generated by no rule", d.ID)
		}
	}
}

// A rule and an alarm file colliding on an id is an error naming BOTH
// sources — the composeTags rule, for the composeTags reason: last-wins
// reads fine on the day it is written and rots silently once the generator
// that emitted one side changes.
func TestAlarmFilesDuplicateIDIsAnError(t *testing.T) {
	proj, rt := loadAlarms(t, alarmFS(alarmTags+`
alarms:
  defs:
    - { id: RTU9_WEL15_INT_001_YA, tag: RTU9_WEL15_INT_001_YA }
alarm-files: [alarms/rtu9.yaml]
`, map[string]string{
		"alarms/rtu9.yaml": "- { id: RTU9_WEL15_INT_001_YA, tag: RTU9_WEL15_INT_001_YA }\n",
	}))
	_, err := proj.AlarmDefs(rt)
	if err == nil {
		t.Fatal("an id declared in both an alarm file and the manifest was accepted")
	}
	if !strings.Contains(err.Error(), "RTU9_WEL15_INT_001_YA") ||
		!strings.Contains(err.Error(), "declared by both") {
		t.Errorf("error should name the id and both sources, got: %v", err)
	}
}

// An alarm file composes like a tag file: its rules and defs come first,
// the manifest's own last.
func TestAlarmFilesCompose(t *testing.T) {
	proj, rt := loadAlarms(t, alarmFS(alarmTags+`
alarms:
  defs:
    - { id: intrusion, tag: RTU9_WEL15_INT_001_YA }
alarm-files: [alarms/rtu9.yaml]
`, map[string]string{
		"alarms/rtu9.yaml": `
- match: { type: AnalogInput, member: HH }
  priority: high
- { id: online-lost, tag: RTU9__Online, name: "RTU 9 offline", priority: critical }
`,
	}))
	defs, err := proj.AlarmDefs(rt)
	if err != nil {
		t.Fatal(err)
	}
	if len(defs) != 3 {
		t.Fatalf("got %d definitions, want 3 (a rule from the file, a def from the file, "+
			"a def from the manifest): %+v", len(defs), defs)
	}
}

// A mistyped placeholder fails the LOAD. The alternative is "{sight}"
// reaching an operator screen as literal braces, which nothing downstream
// can recover from.
func TestBadTemplateFailsAtLoad(t *testing.T) {
	proj, rt := loadAlarms(t, alarmFS(alarmTags+`
alarms:
  rules:
    - match: { type: AnalogInput, member: HH }
      name: "{desc} at {sight}"
`, nil))
	_, err := proj.AlarmDefs(rt)
	if err == nil {
		t.Fatal("a rule naming an unknown placeholder was accepted")
	}
	if !strings.Contains(err.Error(), "sight") {
		t.Errorf("error should name the bad placeholder, got: %v", err)
	}
}

// CheckAlarms is the offline pass `nautilus check` runs. A member the type
// does not have is an ERROR — the type is right here in the project, and
// nothing at run time can make it appear.
func TestCheckAlarmsCatchesUnknownMember(t *testing.T) {
	proj, rt := loadAlarms(t, alarmFS(alarmTags+`
alarms:
  defs:
    - { id: bad, tag: RTU9_WEL15_FIT_001.HHH }
    - { id: notbool, tag: RTU9_WEL15_FIT_001.PV }
`, nil))
	_, errs, _, err := proj.CheckAlarms(rt)
	if err != nil {
		t.Fatal(err)
	}
	if len(errs) != 2 {
		t.Fatalf("want 2 errors (unknown member, non-BOOL member), got %d: %v", len(errs), errs)
	}
	if !strings.Contains(errs[0], "HHH") || !strings.Contains(errs[0], "has: PV, HH, L") {
		t.Errorf("the unknown-member error should list what the type actually has: %s", errs[0])
	}
	if !strings.Contains(errs[1], "not a BOOL") {
		t.Errorf("a non-BOOL condition should say so: %s", errs[1])
	}
}

// A tag this manifest does not declare is a WARNING, not an error: on a
// Sparkplug host most tags arrive from the field, and a site that has
// never birthed legitimately has none.
func TestCheckAlarmsWarnsOnUndeclaredAndDeadRule(t *testing.T) {
	proj, rt := loadAlarms(t, alarmFS(alarmTags+`
alarms:
  rules:
    - match: { type: Valve, member: FAULT }
  defs:
    - { id: elsewhere, tag: RTU7_PMP01_FAULT }
`, nil))
	_, errs, warns, err := proj.CheckAlarms(rt)
	if err != nil {
		t.Fatal(err)
	}
	if len(errs) != 0 {
		t.Fatalf("nothing here is an error: %v", errs)
	}
	if len(warns) != 2 {
		t.Fatalf("want 2 warnings (undeclared tag, dead rule), got %d: %v", len(warns), warns)
	}
	joined := strings.Join(warns, "\n")
	if !strings.Contains(joined, "RTU7_PMP01_FAULT") || !strings.Contains(joined, "matches no tag") {
		t.Errorf("warnings should name the undeclared tag and the dead rule:\n%s", joined)
	}
}

// A project with no `alarms:` has no engine and behaves exactly as it did
// before any of this existed — the compatibility claim, asserted.
func TestNoAlarmsSectionMeansNoEngine(t *testing.T) {
	proj, rt := loadAlarms(t, alarmFS(alarmTags, nil))
	if proj.Alarms != nil {
		t.Fatalf("a manifest with no alarms: section produced %+v", proj.Alarms)
	}
	defs, err := proj.AlarmDefs(rt)
	if err != nil || defs != nil {
		t.Errorf("AlarmDefs = %v, %v; want nil, nil", defs, err)
	}
	eng, err := proj.AlarmEngine(rt)
	if err != nil || eng != nil {
		t.Errorf("AlarmEngine = %v, %v; want nil, nil", eng, err)
	}
	a, err := proj.NewAlarms(rt)
	if err != nil || a != nil {
		t.Errorf("NewAlarms = %v, %v; want nil, nil", a, err)
	}
}

// The engine reads through Tags.ReadPath and evaluates on the runtime's
// post-scan hook, so one Scan() is all it takes for a condition to be
// seen. This is the wiring, end to end, in nine lines.
func TestEngineEvaluatesOnScan(t *testing.T) {
	proj, rt := loadAlarms(t, alarmFS(alarmTags+`
alarms:
  rules:
    - match: { type: AnalogInput, member: HH }
      priority: high
`, nil))
	eng, err := proj.AlarmEngine(rt)
	if err != nil {
		t.Fatal(err)
	}
	defer eng.Close()

	rt.Tags().SetPath("RTU9_WEL15_FIT_001.PV", 150.0)
	rt.Scan()
	if got := eng.Summary().Active; got != 1 {
		t.Fatalf("after one scan over a tripped limit, active = %d, want 1", got)
	}
	if n, err := eng.Ack(nil, "test"); err != nil || n != 1 {
		t.Fatalf("Ack = %d, %v; want 1, nil", n, err)
	}
	if got := eng.Summary().Unacked; got != 0 {
		t.Errorf("unacked = %d after acking everything, want 0", got)
	}
}

// Secrets are environment variables, never the manifest: a postgres
// journal with nothing in the environment fails with that as the reason
// rather than silently running without a durable sink.
func TestPostgresJournalNeedsAnEnvironmentVariable(t *testing.T) {
	proj, rt := loadAlarms(t, alarmFS(alarmTags+`
alarms:
  journal: { sink: postgres }
  defs:
    - { id: a, tag: RTU9_WEL15_INT_001_YA }
`, nil))
	t.Setenv(DefaultAlarmDSNEnv, "")
	t.Setenv(FallbackAlarmDSNEnv, "")
	if _, err := proj.NewAlarms(rt); err == nil ||
		!strings.Contains(err.Error(), DefaultAlarmDSNEnv) {
		t.Errorf("want an error naming %s, got %v", DefaultAlarmDSNEnv, err)
	}
	// The in-memory build ignores the sink entirely, which is what lets a
	// test run against a project configured for a real database.
	eng, err := proj.AlarmEngine(rt)
	if err != nil {
		t.Fatalf("AlarmEngine opened the durable sink: %v", err)
	}
	eng.Close()
}

// site-from must carry a capture group: the FIRST group is the value, and
// a pattern with none would silently give every definition an empty site.
func TestSiteFromNeedsACaptureGroup(t *testing.T) {
	_, err := Load(alarmFS(alarmTags+`
alarms:
  site-from: "^RTU[0-9]+"
`, nil), "")
	if err == nil || !strings.Contains(err.Error(), "capture group") {
		t.Errorf("want a capture-group error, got %v", err)
	}
}
