// manifest.go is the committed description of what a project reads over
// Redfish: the BMCs it polls (sources), the struct tags it builds from
// their resources (tags), and the rare hand-added command (writes).
// Generated by `naut redfish import`; validated offline in New, so `naut
// check` and `build` pass with no BMC in sight. docs/design/it-drivers.md
// §3.2 and §6.
//
// Keys are the brief's dashed manifest keys (`password-env`, `stale-after`,
// `scan-class`) — the vocabulary hw.Binding already speaks through its yaml
// tags, embedded inline in every member binding so the three IT manifests
// decode `map`/`eq`/`scale`/`rate`/`derived` identically. Decoding is
// KnownFields(true): a typo is an error, not a silently dropped binding.
// The generator renders the file by hand (codegen.ManifestYAML), so the
// struct tags here only ever decode.
//
// Credentials never appear in a manifest: a source names its password by
// `password-env: VAR` or `password-file: /run/secrets/bmc` (a mounted k8s
// Secret), never both. An unset variable is not an error here — `naut
// check` runs on laptops without the secrets, so it is a Warning, and the
// driver reports it on the source's status row when it tries to log in.
package redfish

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"net/url"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/joyautomation/nautilus/hw"
	"github.com/joyautomation/nautilus/lang/ir"
)

// Manifest is one project's Redfish surface.
type Manifest struct {
	Sources []Source `yaml:"sources"`
	Tags    []Tag    `yaml:"tags"`
	// Writes are opt-in commands, never generated (brief §7): a person adds
	// one by hand in a reviewed diff.
	Writes []Write `yaml:"writes,omitempty"`
}

// Source is one BMC: one Redfish service, one HTTP client, one session.
type Source struct {
	// ID names the source and prefixes its companions (<id>__Online).
	ID string `yaml:"id"`
	// Host is the service's base URL: "https://bmc1", "https://10.0.0.5:8443".
	// No scheme means https; http:// is accepted for mockups and lab
	// stand-ins. The path is always /redfish/v1 and never part of Host.
	Host string `yaml:"host"`
	// User names the account. It is not a secret; the password is.
	User string `yaml:"user,omitempty"`
	// PasswordEnv / PasswordFile name where the password lives. Exactly one
	// when User is set.
	PasswordEnv  string `yaml:"password-env,omitempty"`
	PasswordFile string `yaml:"password-file,omitempty"`
	// Auth is auto (default: a session, falling back to basic auth when the
	// service refuses sessions), session, basic, or none.
	Auth string `yaml:"auth,omitempty"`
	// TLS: BMCs ship self-signed certificates. The default verifies; set
	// insecure: true or ca-file: to accept the BMC's.
	TLS TLS `yaml:"tls,omitempty"`
	// Timeout bounds one HTTP request (default 10s).
	Timeout time.Duration `yaml:"timeout,omitempty"`
	// Retries is how many extra attempts one GET gets on a transport
	// failure before the poll fails (default 0: a TCP request that timed out
	// rarely answers the second time, and the next poll comes anyway).
	Retries int `yaml:"retries,omitempty"`
	// Interval is this source's default-class poll interval (0 = the
	// driver's scan rate, 10s by default — BMCs rate-limit).
	Interval time.Duration `yaml:"interval,omitempty"`
	// StaleAfter: no complete poll for this long reads Stale even while
	// "connected" (default 3×Interval).
	StaleAfter time.Duration `yaml:"stale-after,omitempty"`
	// Enable names an optional BOOL tag; false parks the source.
	Enable string `yaml:"enable,omitempty"`
}

// TLS is a source's certificate policy.
type TLS struct {
	Insecure bool   `yaml:"insecure,omitempty"`
	CAFile   string `yaml:"ca-file,omitempty"`
}

// Tag is one struct tag of a contract type (hw.Types) built from one
// source's resources.
type Tag struct {
	Name   string `yaml:"name"`
	Type   string `yaml:"type"`
	Source string `yaml:"source"`
	// Desc rides into the tag file (the importer writes the device's own
	// name for the part: "FAN3", "PSU1", "CPU Temp").
	Desc string `yaml:"desc,omitempty"`
	// Resource is the default resource of every member that names none —
	// a fan's members all live in one resource, so the file says it once.
	Resource string                   `yaml:"resource,omitempty"`
	Members  map[string]MemberBinding `yaml:"members"`
}

// MemberBinding is one member's locator — a resource and a path in it —
// plus the shared hw.Binding vocabulary, inline.
type MemberBinding struct {
	// Resource overrides the tag's default resource.
	Resource string `yaml:"resource,omitempty"`
	// Path locates the value in the resource (path.go's grammar).
	Path string `yaml:"path,omitempty"`
	// Agg folds a [*] path's values into one: max, min, sum or count.
	Agg string `yaml:"agg,omitempty"`
	// Exists makes a BOOL member that tests the path instead of reading
	// it: exists: true is true when the path resolves to a non-null value,
	// exists: false when it does not (a sensor whose Reading went null is
	// TempSensor.Fault). It answers the one question a Redfish body asks
	// that a value binding cannot: "is it there at all".
	Exists *bool `yaml:"exists,omitempty"`

	hw.Binding `yaml:",inline"`
}

// Write is an opt-in command: a scalar INT output tag whose change to a
// non-zero value POSTs ComputerSystem.Reset (brief §7). Never generated.
type Write struct {
	// Name is the command tag ("NODE1_PowerCmd"): 0 none, 1 On,
	// 2 GracefulShutdown, 3 ForceOff, 4 GracefulRestart.
	Name string `yaml:"name"`
	// Tag is the Server struct tag the command acts on; Member is its
	// read-back (PowerOn), named so a reviewer sees what confirms it.
	Tag    string `yaml:"tag"`
	Member string `yaml:"member,omitempty"`
	// Target is the action URI, from the System's Actions block.
	Target string `yaml:"target"`
}

// ResetTypes maps a PowerCmd value to the Redfish ResetType it posts.
var ResetTypes = map[int64]string{1: "On", 2: "GracefulShutdown", 3: "ForceOff", 4: "GracefulRestart"}

// Aggregations a [*] path may fold with.
var aggs = []string{"count", "max", "min", "sum"}

// Auth modes.
const (
	AuthAuto    = "auto"
	AuthSession = "session"
	AuthBasic   = "basic"
	AuthNone    = "none"
)

// ── YAML ─────────────────────────────────────────────────────────────────

// LoadManifest decodes a redfish_manifest.yaml without validating it —
// New validates, and a generator may want to load and re-render a manifest
// that is not yet consistent.
func LoadManifest(r io.Reader) (Manifest, error) {
	var m Manifest
	dec := yaml.NewDecoder(r)
	dec.KnownFields(true)
	if err := dec.Decode(&m); err != nil {
		if errors.Is(err, io.EOF) {
			return Manifest{}, errors.New("redfish: manifest is empty")
		}
		return Manifest{}, fmt.Errorf("redfish: manifest: %w", err)
	}
	return m, nil
}

// ParseManifest decodes a manifest from bytes.
func ParseManifest(data []byte) (Manifest, error) { return LoadManifest(bytes.NewReader(data)) }

// ── validation ───────────────────────────────────────────────────────────

var idRE = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// Validate checks everything that can be checked without the BMC:
// references resolve, paths parse, bindings suit their members, and
// credentials are named properly (not that they are set — see Warnings).
// Every finding is reported at once (errors.Join).
func (m Manifest) Validate() error {
	var errs []error
	add := func(format string, a ...any) { errs = append(errs, fmt.Errorf(format, a...)) }

	byID := map[string]bool{}
	for _, s := range m.Sources {
		if s.ID == "" {
			add("source with host %q: missing id", s.Host)
			continue
		}
		if byID[s.ID] {
			add("duplicate source id %q", s.ID)
			continue
		}
		byID[s.ID] = true
		if !idRE.MatchString(s.ID) {
			add("source %s: id must be [A-Za-z0-9_] (it prefixes the %s companion tag)", s.ID, hw.OnlineTagName(s.ID))
		}
		if _, err := s.BaseURL(); err != nil {
			add("source %s: %v", s.ID, err)
		}
		switch s.Auth {
		case "", AuthAuto, AuthSession, AuthBasic:
			if s.User == "" && (s.PasswordEnv != "" || s.PasswordFile != "") {
				add("source %s: a password without a user", s.ID)
			}
			if s.User != "" && s.PasswordEnv == "" && s.PasswordFile == "" {
				add("source %s: user %q needs password-env: VAR or password-file: path (never the password itself)", s.ID, s.User)
			}
			if s.Auth != "" && s.Auth != AuthAuto && s.User == "" {
				add("source %s: auth: %s needs a user", s.ID, s.Auth)
			}
		case AuthNone:
			if s.User != "" || s.PasswordEnv != "" || s.PasswordFile != "" {
				add("source %s: auth: none with credentials", s.ID)
			}
		default:
			add("source %s: auth %q (want auto, session, basic or none)", s.ID, s.Auth)
		}
		if s.PasswordEnv != "" && s.PasswordFile != "" {
			add("source %s: password-env and password-file are alternatives — name one", s.ID)
		}
		if s.PasswordEnv != "" && !idRE.MatchString(s.PasswordEnv) {
			add("source %s: password-env %q is not an environment variable name (it names the variable, never holds the password)", s.ID, s.PasswordEnv)
		}
		if s.TLS.Insecure && s.TLS.CAFile != "" {
			add("source %s: tls: insecure and ca-file are alternatives — ca-file verifies, insecure does not", s.ID)
		}
		if s.Timeout < 0 || s.Interval < 0 || s.StaleAfter < 0 {
			add("source %s: negative duration", s.ID)
		}
		if s.Retries < 0 {
			add("source %s: negative retries", s.ID)
		}
	}

	tagType := map[string]string{}
	for _, t := range m.Tags {
		if t.Name == "" {
			add("a tag on source %q has no name", t.Source)
			continue
		}
		if _, dup := tagType[t.Name]; dup {
			add("duplicate tag %q", t.Name)
			continue
		}
		tagType[t.Name] = t.Type
		if !byID[t.Source] {
			add("tag %s: unknown source %q", t.Name, t.Source)
		}
		if _, ok := hw.TypeByName(t.Type); !ok {
			add("tag %s: unknown type %q (the IT-hardware set is %s)", t.Name, t.Type, hw.TypeNames())
			continue
		}
		if t.Resource != "" {
			if err := checkResource(t.Resource); err != nil {
				add("tag %s: resource: %v", t.Name, err)
			}
		}
		for _, name := range sortedKeys(t.Members) {
			if err := t.Members[name].validate(t, name); err != nil {
				add("tag %s: member %s: %v", t.Name, name, err)
			}
		}
	}

	names := map[string]bool{}
	for _, w := range m.Writes {
		switch {
		case w.Name == "":
			add("a write on tag %q has no name", w.Tag)
			continue
		case names[w.Name]:
			add("duplicate write %q", w.Name)
			continue
		}
		names[w.Name] = true
		if _, clash := tagType[w.Name]; clash {
			add("write %s: same name as a struct tag — a command is its own scalar tag", w.Name)
		}
		typ, ok := tagType[w.Tag]
		switch {
		case !ok:
			add("write %s: unknown tag %q", w.Name, w.Tag)
		case typ != "Server":
			add("write %s: tag %s is a %s — ComputerSystem.Reset acts on a Server", w.Name, w.Tag, typ)
		}
		if w.Member != "" && w.Member != "PowerOn" {
			add("write %s: member %q — a reset command reads back through PowerOn", w.Name, w.Member)
		}
		if err := checkResource(w.Target); err != nil {
			add("write %s: target: %v", w.Name, err)
		} else if !strings.HasSuffix(w.Target, "/Actions/ComputerSystem.Reset") {
			add("write %s: target %q is not a ComputerSystem.Reset action", w.Name, w.Target)
		}
	}
	return errors.Join(errs...)
}

func (b MemberBinding) validate(t Tag, member string) error {
	_, f, ok := hw.FieldOf(t.Type, member)
	if !ok {
		return fmt.Errorf("type %s has no member %q", t.Type, member)
	}
	if err := b.Binding.Validate(f); err != nil {
		return errors.New(strings.TrimPrefix(err.Error(), "member "+member+": "))
	}
	if b.IsStatic() {
		if b.Resource != "" || b.Path != "" || b.Agg != "" || b.Exists != nil {
			return errors.New("const:/derived: take no resource/path/agg/exists")
		}
		return nil
	}
	res := b.Resource
	if res == "" {
		res = t.Resource
	}
	if res == "" {
		return errors.New("no resource (on the member or the tag)")
	}
	if err := checkResource(res); err != nil {
		return fmt.Errorf("resource: %w", err)
	}
	if b.Path == "" {
		return errors.New("no path")
	}
	p, err := ParsePath(b.Path)
	if err != nil {
		return err
	}
	if b.Agg != "" {
		if !contains(aggs, b.Agg) {
			return fmt.Errorf("agg %q (want %s)", b.Agg, strings.Join(aggs, ", "))
		}
		if f.Kind != ir.TypeReal && f.Kind != ir.TypeInt {
			return fmt.Errorf("agg: needs a numeric member, not %s", f.Kind)
		}
		if b.Map != nil || b.Eq != nil {
			return errors.New("agg: takes no map/eq")
		}
	}
	if p.Wildcard() && b.Agg == "" {
		return fmt.Errorf("path %q fans out with [*] — add agg: max|min|sum|count", b.Path)
	}
	if b.Exists != nil {
		if f.Kind != ir.TypeBool {
			return fmt.Errorf("exists: makes a BOOL, but the member is %s", f.Kind)
		}
		if b.Map != nil || b.Eq != nil || b.Rate || b.Scale != 0 || b.Offset != 0 || b.Agg != "" {
			return errors.New("exists: takes no map/eq/rate/scale/offset/agg")
		}
	}
	return nil
}

// checkResource: an absolute /redfish/v1 URI with no fragment — a
// "Thermal#/Fans/0" id names a place inside a body, which is what path: is
// for; it cannot be fetched.
func checkResource(r string) error {
	switch {
	case !strings.HasPrefix(r, "/redfish/v1"):
		return fmt.Errorf("%q must start with /redfish/v1", r)
	case strings.ContainsAny(r, "#?"):
		return fmt.Errorf("%q: a resource has no fragment or query — select inside it with path:", r)
	case strings.HasSuffix(r, "/") && r != "/redfish/v1/":
		return fmt.Errorf("%q: no trailing slash", r)
	}
	return nil
}

// BaseURL parses Host: scheme (https by default) and authority only.
func (s Source) BaseURL() (*url.URL, error) {
	h := strings.TrimSpace(s.Host)
	if h == "" {
		return nil, errors.New("missing host")
	}
	if !strings.Contains(h, "://") {
		h = "https://" + h
	}
	u, err := url.Parse(h)
	if err != nil {
		return nil, fmt.Errorf("host %q: %v", s.Host, err)
	}
	if u.Scheme != "https" && u.Scheme != "http" {
		return nil, fmt.Errorf("host %q: scheme %q (want https, or http for a mockup)", s.Host, u.Scheme)
	}
	if u.User != nil {
		// Never echo the userinfo back: it may hold the password.
		return nil, errors.New("host carries credentials — use user: and password-env:/password-file: instead")
	}
	if u.Host == "" {
		return nil, fmt.Errorf("host %q: no host name", s.Host)
	}
	if (u.Path != "" && u.Path != "/") || u.RawQuery != "" || u.Fragment != "" {
		return nil, fmt.Errorf("host %q: just scheme://host[:port] — the /redfish/v1 path is implied", s.Host)
	}
	return &url.URL{Scheme: u.Scheme, Host: u.Host}, nil
}

// Warnings lists the conditions `naut check` should print but not fail
// on: a named password variable that is unset, a password file that
// cannot be read. Never the value — only which name is missing.
func (m Manifest) Warnings() []string {
	var out []string
	for _, s := range m.Sources {
		switch {
		case s.PasswordEnv != "":
			if _, ok := os.LookupEnv(s.PasswordEnv); !ok {
				out = append(out, fmt.Sprintf("redfish source %s: password-env %s is not set — the driver cannot log in until it is", s.ID, s.PasswordEnv))
			}
		case s.PasswordFile != "":
			if _, err := os.Stat(s.PasswordFile); err != nil {
				out = append(out, fmt.Sprintf("redfish source %s: password-file %s is not readable here (%v)", s.ID, s.PasswordFile, cause(err)))
			}
		}
		if s.TLS.CAFile != "" {
			if _, err := os.Stat(s.TLS.CAFile); err != nil {
				out = append(out, fmt.Sprintf("redfish source %s: tls ca-file %s is not readable here", s.ID, s.TLS.CAFile))
			}
		}
	}
	return out
}

// password resolves the source's secret at use time. The error names the
// variable or file, never a value.
func (s Source) password() (string, error) {
	switch {
	case s.PasswordEnv != "":
		v, ok := os.LookupEnv(s.PasswordEnv)
		if !ok {
			return "", fmt.Errorf("password-env %s is not set", s.PasswordEnv)
		}
		return v, nil
	case s.PasswordFile != "":
		b, err := os.ReadFile(s.PasswordFile)
		if err != nil {
			return "", fmt.Errorf("password-file %s: %v", s.PasswordFile, cause(err))
		}
		return strings.TrimRight(string(b), "\r\n"), nil
	}
	return "", nil
}

// cause drops an *os.PathError's path (the message already names the
// file) and keeps the reason; anything else passes through.
func cause(err error) error {
	if u := errors.Unwrap(err); u != nil {
		return u
	}
	return err
}

// resourceOf is the member's effective resource.
func (b MemberBinding) resourceOf(t Tag) string {
	if b.Resource != "" {
		return b.Resource
	}
	return t.Resource
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func contains(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}
