// Package importer turns a Logix L5X export into a nautilus project —
// the brownfield direction of docs/design/logix-authoring.md: the plant
// already has the code, and "ditch the IDE" has to start from it.
//
// The import is the writer's mapping run backwards. A rung of neutral
// text becomes a nautilus rung; a TIMER tag driven by TON becomes a TON
// instance with its preset from the tag's value; the one-shot and reset
// idioms the writer emits fold back into the +Name / R := forms they came
// from; an Add-On Instruction becomes a FUNCTION_BLOCK in lib/. What has
// no nautilus form yet — a MOVE, an ADD, a CMP expression, a JSR — is NOT
// guessed at: the rung is left out of the program, its text kept in a
// comment where it stood, and the report says so. A program with a rung
// left out is not deployable as it is, and the file's header says that
// too.
//
// Nothing here is byte-exact: Logix has no rung names, nautilus has no
// rung numbers, and the generated edge tags are renamed by the trip. The
// test of a good import is `writer.Write(import(doc))` producing the same
// rung text as doc, modulo those names — which is what the tests check.
package importer

import (
	"fmt"
	"sort"
	"strings"

	"github.com/joyautomation/nautilus/internal/tagfile"
	"github.com/joyautomation/nautilus/lang/l5x"
)

// Options steer an import.
type Options struct {
	// Programs limits the import to these Logix programs; empty imports
	// every program in the export.
	Programs []string
	// Name is the project name in the manifest; default the controller's.
	Name string
	// CommPath and Host go into the manifest's target: logix section,
	// so an imported project can deploy back where it came from.
	CommPath string
	Host     string
}

// Note is one thing the import could not carry, or changed.
type Note struct {
	// Owner is "Program/Routine", "AOI:Name", or "" for the project.
	Owner string
	// Rung is the Logix rung number, or -1 when the note is not about one.
	Rung int
	// Reason is a short, stable key: the instruction mnemonic for a rung
	// with no nautilus form, or a word for a structural change.
	Reason string
	// Text is the detail: the rung text, the tag, the explanation.
	Text string
}

func (n Note) String() string {
	where := n.Owner
	if n.Rung >= 0 {
		where = fmt.Sprintf("%s rung %d", n.Owner, n.Rung)
	}
	if where == "" {
		return n.Reason + ": " + n.Text
	}
	return where + ": " + n.Reason + ": " + n.Text
}

// Project is the import's result: the files to write, relative to the
// project root, and what the report says.
type Project struct {
	Files map[string][]byte
	Notes []Note
	// Routines counts the ladder routines imported, Complete the ones
	// with every rung carried; Rungs and Imported count rungs.
	Routines, Complete int
	Rungs, Imported    int
}

// Import converts the export.
func Import(f *l5x.File, opts Options) (*Project, error) {
	if f == nil || f.Controller == nil {
		return nil, fmt.Errorf("importer: no controller in the export")
	}
	c := f.Controller
	p := &Project{Files: map[string][]byte{}}
	im := &importer{file: f, opts: opts, proj: p, aois: map[string]*l5x.AddOnInstruction{}, ctrl: map[string]*l5x.Tag{}}
	for _, a := range c.AOIs {
		im.aois[strings.ToLower(a.Name)] = a
	}
	for _, t := range c.Tags {
		im.ctrl[strings.ToLower(t.Name)] = t
	}

	// Types first: the tags and the declarations refer to them by name.
	typesSrc, unresolved, err := l5x.Types(f, l5x.TypesOptions{})
	if err != nil {
		return nil, err
	}
	for _, u := range unresolved {
		p.note("", -1, "type", u+": no public shape; members of it are omitted")
	}
	im.types = declaredTypes(typesSrc)
	if strings.TrimSpace(typesSrc) != "" {
		p.Files["lib/logix_types.st"] = []byte("(* Generated by `naut logix import` from the " + c.Name + " export: the\n   project's user-defined types. Do not edit; re-run the import. *)\n\n" + typesSrc)
	}

	// Add-On Instructions: a FUNCTION_BLOCK each, in lib/.
	for _, a := range c.AOIs {
		im.importAOI(a)
	}

	// Programs: a PROGRAM per routine.
	selected := map[string]bool{}
	for _, n := range opts.Programs {
		selected[strings.ToLower(n)] = true
	}
	scheduled := map[string]*l5x.Task{}
	for _, t := range c.Tasks {
		for _, n := range t.Programs {
			scheduled[strings.ToLower(n)] = t
		}
	}
	var tasks []manifestTask
	for _, prog := range c.Programs {
		if len(selected) > 0 && !selected[strings.ToLower(prog.Name)] {
			continue
		}
		task := scheduled[strings.ToLower(prog.Name)]
		if task == nil {
			p.note(prog.Name, -1, "unscheduled", "the program is in no task; imported with the default scan")
		}
		for _, file := range im.importProgram(prog) {
			tasks = append(tasks, manifestTask{File: file, Task: task})
		}
	}

	// Controller tags: the generated tag file, with roles refined by what
	// the imported logic writes.
	tags, err := l5x.Tags(f, l5x.TagsOptions{Scope: "", KnownTypes: im.types})
	if err != nil {
		return nil, err
	}
	for i := range tags {
		if im.written[strings.ToLower(tags[i].Name)] {
			tags[i].Role = "output"
		}
	}
	header := []string{
		"Generated by `naut logix import` from the " + c.Name + " export.",
		"Do not edit; re-run the import.",
		"",
		"role: is output for a tag the imported logic writes, input for the",
		"rest. desc: is the offline project's own tag documentation.",
	}
	raw, err := tagfile.Render(header, tags)
	if err != nil {
		return nil, err
	}
	p.Files["tags/logix.yaml"] = raw
	p.Files["nautilus.yaml"] = im.manifest(tasks)
	sort.Slice(p.Notes, func(i, j int) bool {
		if p.Notes[i].Owner != p.Notes[j].Owner {
			return p.Notes[i].Owner < p.Notes[j].Owner
		}
		return p.Notes[i].Rung < p.Notes[j].Rung
	})
	return p, nil
}

func (p *Project) note(owner string, rung int, reason, text string) {
	p.Notes = append(p.Notes, Note{Owner: owner, Rung: rung, Reason: reason, Text: text})
}

// Reasons is the histogram of rung-level notes: what kept rungs out, by
// instruction or structure, most frequent first.
func (p *Project) Reasons() []string {
	count := map[string]int{}
	for _, n := range p.Notes {
		if n.Rung >= 0 {
			count[n.Reason]++
		}
	}
	keys := make([]string, 0, len(count))
	for k := range count {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if count[keys[i]] != count[keys[j]] {
			return count[keys[i]] > count[keys[j]]
		}
		return keys[i] < keys[j]
	})
	out := make([]string, 0, len(keys))
	for _, k := range keys {
		out = append(out, fmt.Sprintf("%s %d", k, count[k]))
	}
	return out
}

type importer struct {
	file  *l5x.File
	opts  Options
	proj  *Project
	aois  map[string]*l5x.AddOnInstruction
	ctrl  map[string]*l5x.Tag
	types map[string]bool
	// written collects controller tags the imported logic drives, for
	// the tag file's roles.
	written map[string]bool
	// used marks file names taken, so two routines never collide.
	used map[string]bool
}

// declaredTypes lists the names a generated ST file declares: the
// `Name : STRUCT` lines inside TYPE … END_TYPE.
func declaredTypes(src string) map[string]bool {
	out := map[string]bool{}
	for _, line := range strings.Split(src, "\n") {
		line = strings.TrimSpace(line)
		if i := strings.Index(line, ":"); i > 0 && strings.Contains(line[i:], "STRUCT") {
			if name := strings.TrimSpace(line[:i]); name != "" && !strings.Contains(name, " ") {
				out[name] = true
			}
		}
	}
	return out
}

type manifestTask struct {
	File string
	Task *l5x.Task
}

func (im *importer) manifest(tasks []manifestTask) []byte {
	c := im.file.Controller
	name := im.opts.Name
	if name == "" {
		name = strings.ToLower(l5x.Ident(c.Name))
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Imported from the %s export by `naut logix import`. The programs are\n", c.Name)
	b.WriteString("# nautilus source now: edit them, `naut check --target logix`, and deploy\n")
	b.WriteString("# with `naut logix deploy`. Rungs the import could not carry are kept as\n")
	b.WriteString("# comments in the program files; the import's report lists them.\n")
	fmt.Fprintf(&b, "name: %s\n", name)
	b.WriteString("tasks:\n")
	if len(tasks) == 0 {
		b.WriteString("  []\n")
	}
	for _, t := range tasks {
		scan := "10ms"
		if t.Task != nil && t.Task.Type == "PERIODIC" && t.Task.RateMs > 0 {
			scan = fmt.Sprintf("%gms", t.Task.RateMs)
		}
		fmt.Fprintf(&b, "  - program: %s\n    scan: %s", t.File, scan)
		if t.Task == nil {
			b.WriteString(" # unscheduled in the export")
		} else if t.Task.Type != "PERIODIC" {
			fmt.Fprintf(&b, " # %s task %s in the export", strings.ToLower(t.Task.Type), t.Task.Name)
		}
		b.WriteString("\n")
	}
	b.WriteString("tag-files: [tags/logix.yaml]\n")
	b.WriteString("target:\n  logix:\n")
	fmt.Fprintf(&b, "    controller: %s\n", c.Name)
	if c.ProcessorType != "" {
		fmt.Fprintf(&b, "    processor: %s\n", c.ProcessorType)
	}
	if c.MajorRev != "" {
		minor := c.MinorRev
		if minor == "" {
			minor = "11"
		}
		fmt.Fprintf(&b, "    revision: \"%s.%s\"\n", c.MajorRev, minor)
	}
	if im.opts.CommPath != "" {
		fmt.Fprintf(&b, "    comm-path: %s\n", im.opts.CommPath)
	}
	if im.opts.Host != "" {
		fmt.Fprintf(&b, "    host: %s\n", im.opts.Host)
	}
	if len(tasks) == 1 {
		// One program: tell the writer its Logix names, so a deploy puts
		// it back where it was.
		if t := tasks[0]; t.Task != nil {
			fmt.Fprintf(&b, "    task: %s\n", t.Task.Name)
		}
	}
	return []byte(b.String())
}

func (im *importer) fileName(base, ext string) string {
	if im.used == nil {
		im.used = map[string]bool{}
	}
	name := base + ext
	for i := 2; im.used[strings.ToLower(name)]; i++ {
		name = fmt.Sprintf("%s_%d%s", base, i, ext)
	}
	im.used[strings.ToLower(name)] = true
	return name
}
