#!/usr/bin/env python3
"""The same generator, in Python.

    python3 tools/tags.py

Standard library only — no pip, no venv, no requirements.txt. This is the
version to hand a controls engineer who has neither Go nor Node but does have
the Python that ships with their machine.
"""

import json

# ── 1. what varies per pump ────────────────────────────────────────────────
pumps = [
    ("P101", "Filter backwash pump 1"),
    ("P102", "Filter backwash pump 2"),
    ("P103", "Filter backwash pump 3"),
    ("P201", "Transfer pump 1"),
    ("P202", "Transfer pump 2"),
    ("P301", "High service pump"),
]

# ── 2. what every pump gets, derived ───────────────────────────────────────
per_pump = [
    ("RunHrs", "state", 0.0, "h", "run hours"),
    ("StartSP", "setpoint", 45.0, "%", "start speed"),
    ("Enable", "setpoint", False, "", "operator enable"),
]

udt_role = "state"  # see tools/tags.go for what flipping this to "input" does

# ── 3. the expander ────────────────────────────────────────────────────────
tags = []
for pid, pdesc in pumps:
    tags.append({"name": pid, "role": udt_role, "type": "Motor", "desc": pdesc})
    for suffix, role, init, unit, ddesc in per_pump:
        tags.append({
            "name": f"{pid}_{suffix}",
            "role": role,
            "init": init,
            "unit": unit,
            "desc": f"{pdesc} — {ddesc}",
        })


# ── 4. render ──────────────────────────────────────────────────────────────
def scalar(v):
    # bool before float: in Python, isinstance(True, int) is True, and
    # emitting "1.0" for an enable flag would retype the tag.
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float) and v.is_integer():
        return f"{v:.1f}"
    return json.dumps(v)


def line(t):
    parts = [f"name: {t['name']}", f"role: {t['role']}"]
    if t.get("type"):
        parts.append(f"type: {t['type']}")
    if t.get("init") is not None:
        parts.append(f"init: {scalar(t['init'])}")
    if t.get("unit"):
        parts.append(f"unit: {json.dumps(t['unit'])}")
    if t.get("desc"):
        parts.append(f"desc: {json.dumps(t['desc'], ensure_ascii=False)}")
    return "- { " + ", ".join(parts) + " }"


header = "\n".join([
    "# tags/pumps.yaml — generated by tools/tags.py. Do not edit; re-run it.",
    "#",
    f"# {len(pumps)} pumps x {len(per_pump) + 1} tags each = {len(tags)} tags,",
    f"# from {len(pumps) + len(per_pump)} authored table rows.",
    "",
])

tags.sort(key=lambda t: t["name"])
with open("tags/pumps.yaml", "w") as f:
    f.write(header + "\n".join(line(t) for t in tags) + "\n")
print(f"wrote tags/pumps.yaml — {len(tags)} tags")
