// The same generator, in TypeScript for Deno.
//
//     deno run --allow-write tools/tags.deno.ts
//
// Identical to tools/tags.ts except for the two lines that touch the
// filesystem — which is the point worth noticing. Deno's pull is that it is
// one static binary with no package.json and an explicit permission on the
// write, so a generator can only do the one thing it says it does.
//
// If you already run Deno, use this. If you already run Node, use tags.ts.
// Nautilus cannot tell the difference and does not try.

type Tag = {
  name: string;
  role: string;
  type?: string;
  init?: number | boolean | string;
  unit?: string;
  desc?: string;
};

// ── 1. what varies per pump ────────────────────────────────────────────────
const pumps = [
  { id: "P101", desc: "Filter backwash pump 1" },
  { id: "P102", desc: "Filter backwash pump 2" },
  { id: "P103", desc: "Filter backwash pump 3" },
  { id: "P201", desc: "Transfer pump 1" },
  { id: "P202", desc: "Transfer pump 2" },
  { id: "P301", desc: "High service pump" },
];

// ── 2. what every pump gets, derived ───────────────────────────────────────
const perPump = [
  { suffix: "RunHrs", role: "state", init: 0.0, unit: "h", desc: "run hours" },
  { suffix: "StartSP", role: "setpoint", init: 45.0, unit: "%", desc: "start speed" },
  { suffix: "Enable", role: "setpoint", init: false, desc: "operator enable" },
];

const udtRole = "state"; // see tools/tags.go for what flipping this to "input" does

// ── 3. the expander ────────────────────────────────────────────────────────
const tags: Tag[] = pumps.flatMap((p) => [
  { name: p.id, role: udtRole, type: "Motor", desc: p.desc },
  ...perPump.map((d) => ({
    name: `${p.id}_${d.suffix}`,
    role: d.role,
    init: d.init,
    unit: d.unit,
    desc: `${p.desc} — ${d.desc}`,
  })),
]);

// ── 4. render ──────────────────────────────────────────────────────────────
const quote = (s: string) => JSON.stringify(s);
const scalar = (v: unknown) =>
  typeof v === "number" && Number.isInteger(v) ? v.toFixed(1) : JSON.stringify(v);

const line = (t: Tag) => {
  const parts = [`name: ${t.name}`, `role: ${t.role}`];
  if (t.type) parts.push(`type: ${t.type}`);
  if (t.init !== undefined) parts.push(`init: ${scalar(t.init)}`);
  if (t.unit) parts.push(`unit: ${quote(t.unit)}`);
  if (t.desc) parts.push(`desc: ${quote(t.desc)}`);
  return `- { ${parts.join(", ")} }`;
};

const header = [
  "# tags/pumps.yaml — generated by tools/tags.deno.ts. Do not edit; re-run it.",
  "#",
  `# ${pumps.length} pumps x ${perPump.length + 1} tags each = ${tags.length} tags,`,
  `# from ${pumps.length + perPump.length} authored table rows.`,
  "",
].join("\n");

tags.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
await Deno.writeTextFile("tags/pumps.yaml", header + tags.map(line).join("\n") + "\n");
console.log(`wrote tags/pumps.yaml — ${tags.length} tags`);
