//go:build ignore

// The tag generator for this project, in Go.
//
//	go run tools/tags.go
//
// This file is the thing a person edits. tags/pumps.yaml is not — it is
// output, and it says so in its own header.
//
// The shape is a compact CONFIG TABLE plus an EXPANDER. The table holds only
// what varies between pumps; the expander supplies everything that does not
// (role, type, the absent init, the composed description). Adding a pump is
// one line in pumps; adding a derived tag to EVERY pump is one line in
// perPump.
//
// Four other versions of this exact generator live beside it — tags.ts
// (Node), tags.deno.ts, tags.py, and pumps.csv fed through
// `nautilus tags import-csv`. All five emit an identical tag list, and
// generators_test.go asserts it. That is not a coincidence to admire; it is
// the design. Nautilus never runs your generator — the only exec in the whole
// toolchain is `git init` during scaffolding — so the language is entirely
// your business. Pick one your team already has.
//
// Stdlib only, on purpose. Nautilus has an internal/tagfile package that
// renders exactly this, but a generator in your project could not import it,
// so using it here would make the Go version a privileged peer rather than an
// honest one. The four rules in render() below are the entire contract, and
// they are pinned by the published JSON Schema plus `nautilus check`.
package main

import (
	"cmp"
	"fmt"
	"log"
	"os"
	"slices"
	"strconv"
	"strings"
)

// ── 1. what varies per pump ────────────────────────────────────────────────
var pumps = []struct{ ID, Desc string }{
	{"P101", "Filter backwash pump 1"},
	{"P102", "Filter backwash pump 2"},
	{"P103", "Filter backwash pump 3"},
	{"P201", "Transfer pump 1"},
	{"P202", "Transfer pump 2"},
	{"P301", "High service pump"},
}

// ── 2. what every pump gets, derived ───────────────────────────────────────
var perPump = []struct {
	Suffix, Role string
	Init         any
	Unit, Desc   string
}{
	{"RunHrs", "state", 0.0, "h", "run hours"},
	{"StartSP", "setpoint", 45.0, "%", "start speed"},
	{"Enable", "setpoint", false, "", "operator enable"},
}

// The role of the UDT tag itself is the one thing that differs between this
// simulated demo and a real deployment, so it is a knob rather than a
// hard-coded string:
//
//	state  — seeded with a ZERO Motor (every field present, all zero), which
//	         is what lets sim.st drive it here with no field bus.
//	input  — deliberately UNSEEDED: the field supplies it, and a silent
//	         driver should fault on the first read rather than quietly hand
//	         the logic zeros that look like a healthy stopped pump.
//
// Flip it, re-run, and `nautilus run` reports the difference.
const udtRole = "state"

type tag struct {
	Name, Role, Type string
	Init             any
	Unit, Desc       string
}

func main() {
	// ── 3. the expander ────────────────────────────────────────────────
	var tags []tag
	for _, p := range pumps {
		tags = append(tags, tag{Name: p.ID, Role: udtRole, Type: "Motor", Desc: p.Desc})
		for _, d := range perPump {
			tags = append(tags, tag{
				Name: p.ID + "_" + d.Suffix, Role: d.Role, Init: d.Init,
				Unit: d.Unit, Desc: p.Desc + " — " + d.Desc,
			})
		}
	}

	header := []string{
		"tags/pumps.yaml — generated by tools/tags.go. Do not edit; re-run it.",
		"",
		fmt.Sprintf("%d pumps x %d tags each = %d tags,", len(pumps), len(perPump)+1, len(tags)),
		fmt.Sprintf("from %d authored table rows.", len(pumps)+len(perPump)),
	}
	if err := os.WriteFile("tags/pumps.yaml", render(header, tags), 0o644); err != nil {
		log.Fatalln("tools/tags.go:", err)
	}
	fmt.Printf("wrote tags/pumps.yaml — %d tags\n", len(tags))
}

// ── 4. render ──────────────────────────────────────────────────────────────
// Four rules, and they are the whole contract:
//   - sorted by name, so a regenerated file diffs against the last one
//     instead of reshuffling and burying what changed
//   - whole floats keep a decimal point, or YAML decodes a REAL seed as an
//     int and silently retypes the tag
//   - text is quoted, because a flow mapping ends at the first bare comma
//   - empty fields are omitted rather than emitted blank
func render(header []string, tags []tag) []byte {
	var b strings.Builder
	for _, line := range header {
		if line == "" {
			b.WriteString("#\n")
			continue
		}
		fmt.Fprintf(&b, "# %s\n", line)
	}

	slices.SortStableFunc(tags, func(a, b tag) int { return cmp.Compare(a.Name, b.Name) })

	for _, t := range tags {
		fmt.Fprintf(&b, "- { name: %s, role: %s", t.Name, t.Role)
		if t.Type != "" {
			fmt.Fprintf(&b, ", type: %s", t.Type)
		}
		if t.Init != nil {
			fmt.Fprintf(&b, ", init: %s", scalar(t.Init))
		}
		if t.Unit != "" {
			fmt.Fprintf(&b, ", unit: %s", quote(t.Unit))
		}
		if t.Desc != "" {
			fmt.Fprintf(&b, ", desc: %s", quote(t.Desc))
		}
		b.WriteString(" }\n")
	}
	return []byte(b.String())
}

func scalar(v any) string {
	switch x := v.(type) {
	case bool:
		return strconv.FormatBool(x)
	case float64:
		if x == float64(int64(x)) {
			return fmt.Sprintf("%.1f", x)
		}
		return strconv.FormatFloat(x, 'g', -1, 64)
	case string:
		return quote(x)
	}
	return quote(fmt.Sprint(v))
}

func quote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`)
	return `"` + r.Replace(s) + `"`
}
