// The same generator, in TypeScript for Node.
//
//     node tools/tags.ts
//
// No package.json, no npm install, no tsc, no bundler. Node 22.6+ strips
// types natively, so a .ts file with no runtime dependencies just runs.
// (On older Node: `npx tsx tools/tags.ts`.)
//
// This is the version to copy if your team already lives in Node — which for
// most controls shops with any web tooling, it does.

import { writeFileSync } from "node:fs";

type Tag = {
  name: string;
  role: string;
  type?: string;
  init?: number | boolean | string;
  unit?: string;
  desc?: string;
};

// ── 1. what varies per pump ────────────────────────────────────────────────
const pumps = [
  { id: "P101", desc: "Filter backwash pump 1" },
  { id: "P102", desc: "Filter backwash pump 2" },
  { id: "P103", desc: "Filter backwash pump 3" },
  { id: "P201", desc: "Transfer pump 1" },
  { id: "P202", desc: "Transfer pump 2" },
  { id: "P301", desc: "High service pump" },
];

// ── 2. what every pump gets, derived ───────────────────────────────────────
const perPump = [
  { suffix: "RunHrs", role: "state", init: 0.0, unit: "h", desc: "run hours" },
  { suffix: "StartSP", role: "setpoint", init: 45.0, unit: "%", desc: "start speed" },
  { suffix: "Enable", role: "setpoint", init: false, desc: "operator enable" },
];

// state = seeded with a zero Motor, which lets sim.st drive it with no field
// bus. input = deliberately unseeded, so a silent driver faults on the first
// read instead of handing the logic zeros. See tools/tags.go for the long
// version of this note.
const udtRole = "state";

// ── 3. the expander ────────────────────────────────────────────────────────
const tags: Tag[] = pumps.flatMap((p) => [
  { name: p.id, role: udtRole, type: "Motor", desc: p.desc },
  ...perPump.map((d) => ({
    name: `${p.id}_${d.suffix}`,
    role: d.role,
    init: d.init,
    unit: d.unit,
    desc: `${p.desc} — ${d.desc}`,
  })),
]);

// ── 4. render ──────────────────────────────────────────────────────────────
// These four rules are the whole contract, and they are pinned by the
// published JSON Schema (tools/vscode-iec/schemas/nautilus-tags.schema.json)
// plus `nautilus check`:
//   - sorted by name, so a regenerated file diffs against the last one
//   - whole floats keep a decimal point, or YAML decodes REAL as DINT
//   - text is quoted, because a flow mapping ends at the first bare comma
//   - empty fields are omitted rather than emitted blank
const quote = (s: string) => JSON.stringify(s);
const scalar = (v: unknown) =>
  typeof v === "number" && Number.isInteger(v) ? v.toFixed(1) : JSON.stringify(v);

const line = (t: Tag) => {
  const parts = [`name: ${t.name}`, `role: ${t.role}`];
  if (t.type) parts.push(`type: ${t.type}`);
  if (t.init !== undefined) parts.push(`init: ${scalar(t.init)}`);
  if (t.unit) parts.push(`unit: ${quote(t.unit)}`);
  if (t.desc) parts.push(`desc: ${quote(t.desc)}`);
  return `- { ${parts.join(", ")} }`;
};

const header = [
  "# tags/pumps.yaml — generated by tools/tags.ts. Do not edit; re-run it.",
  "#",
  `# ${pumps.length} pumps x ${perPump.length + 1} tags each = ${tags.length} tags,`,
  `# from ${pumps.length + perPump.length} authored table rows.`,
  "",
].join("\n");

tags.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
writeFileSync("tags/pumps.yaml", header + tags.map(line).join("\n") + "\n");
console.log(`wrote tags/pumps.yaml — ${tags.length} tags`);
