package codegen

// The importer already knows every binding's name, type, and direction, so
// the `tags:` block of nautilus.yaml is derivable rather than transcribed.
// Before this, examples/client60 hand-copied 14 of its 230 bindings — and
// two of the UDT ones could only be described in an English prose desc:,
// because a manifest tag had no way to say "this is an Analog_Input".
//
// Output is a tag FILE (a bare YAML list) rather than a manifest section, so
// it composes through tag-files: and stays a separate reviewable artifact:
// regenerating it never touches the file a person edits.

import (
	"fmt"
	"path"
	"strings"

	"github.com/joyautomation/nautilus/eip"
	"github.com/joyautomation/nautilus/internal/tagfile"
)

// elementary is every Logix scalar name the driver decodes directly. A
// binding of one of these is a plain scalar tag; anything else names a UDT
// the generated eip_types.st declares, which is what `type:` refers to.
var elementary = map[string]bool{
	"BOOL": true, "SINT": true, "INT": true, "DINT": true, "LINT": true,
	"USINT": true, "UINT": true, "UDINT": true, "ULINT": true,
	"REAL": true, "LREAL": true, "STRING": true, "BYTE": true,
	"WORD": true, "DWORD": true, "LWORD": true,
}

// TagsYAML renders the manifest's bindings as a nautilus tag file.
//
// It is a pure function of a committed eip.Manifest — no controller needed —
// so the file can be re-derived from what is already in the repo after the
// import that produced it.
//
// skip holds path.Match globs for bindings to LEAVE OUT. A tag may be
// declared once, so a project that needs to say something the import cannot
// know — most often an `init:` on an input, so the logic runs before the
// first poll instead of faulting — declares that tag by hand and skips it
// here. That is the "narrow the generator's scope" escape hatch, and it
// exists so the alternative (an override that silently survives
// regeneration) never has to.
func TagsYAML(m eip.Manifest, host string, skip []string) ([]byte, error) {
	udt := map[string]bool{}
	for _, t := range m.Types {
		udt[t.Name] = true
	}

	header := []string{
		fmt.Sprintf("Generated by `nautilus eip import --host %s` from the controller's", host),
		"tag list. Do not edit — re-run the import.",
		"",
		"Compose it into a project with:  tag-files: [tags/eip.yaml]",
		"Documentation belongs in nautilus.yaml's tag-meta:, not here — a",
		"Logix controller keeps tag descriptions in its offline project file,",
		"so the import cannot recover them and would overwrite yours.",
	}
	if len(skip) > 0 {
		header = append(header, "",
			"Not generated (declared by hand in the manifest): "+strings.Join(skip, ", "))
	}

	var out []tagfile.Tag
	var skipped int
	for _, t := range m.Tags {
		if t.Name == "" {
			continue
		}
		if matchesAny(t.Name, skip) {
			skipped++
			continue
		}
		tag := tagfile.Tag{Name: t.Name, Role: "input"}
		if t.Writable {
			// Writable bindings are the driver's output set: the runtime's
			// value propagates to the controller. A program that also READS
			// one back needs an init, which the import cannot know — and
			// `nautilus check` reports as a read of an unseeded tag.
			tag.Role = "output"
		}
		// An ARRAY binding's value is an array of the element type, which
		// `type:` (a UDT name) cannot express — so it is left off and the
		// shape comes from the driver. A scalar's type comes from the value
		// the driver delivers, as it always has.
		if t.ArrayLen == 0 && t.Type != "" && !elementary[strings.ToUpper(t.Type)] {
			if !udt[t.Type] {
				return nil, fmt.Errorf("tag %s binds type %q, which the manifest does not "+
					"declare — the generated eip_types.st would not declare it either",
					t.Name, t.Type)
			}
			tag.Type = t.Type
		}
		out = append(out, tag)
	}
	// A skip pattern that matches nothing is almost always a stale exclusion
	// left behind after a tag was renamed on the controller — which silently
	// puts the tag back into the generated file, colliding with the
	// hand-written declaration it was meant to make room for.
	if len(skip) > 0 && skipped == 0 {
		return nil, fmt.Errorf("no binding matches any of the skip patterns (%s) — "+
			"a stale exclusion would silently regenerate a tag you declare by hand",
			strings.Join(skip, ", "))
	}
	return tagfile.Render(header, out)
}

func matchesAny(name string, pats []string) bool {
	for _, p := range pats {
		if ok, err := path.Match(p, name); err == nil && ok {
			return true
		}
	}
	return false
}
