// Package eip is the EtherNet/IP field driver for nautilus: it polls tags on
// an Allen-Bradley Logix controller (ControlLogix / CompactLogix) and exposes
// them through the io.Driver seam, so an ST/Go program consumes device tags —
// including UDT structs and arrays — like any other tag. Connections are
// configured in Go (high-code, like everything in nautilus); the type/tag
// manifest is generated by `nautilus eip import`, which browses the device
// and emits committed source files.
package eip

import (
	"fmt"

	"github.com/joyautomation/nautilus/eip/logix"
	"github.com/joyautomation/nautilus/lang/ir"
)

// Manifest is the committed description of what a project consumes from one
// controller: the UDT shapes it depends on and the tag bindings. Generated by
// `nautilus eip import`; validated against the live controller at startup so
// drift between the PLC program and the generated types fails loudly instead
// of mis-decoding.
type Manifest struct {
	Types []TypeDef
	Tags  []TagBinding
}

// TypeDef mirrors a Logix UDT (or AOI/predefined struct) that bound tags use.
// Fields appear in template wire order.
type TypeDef struct {
	Name   string
	Fields []FieldDef
}

// FieldDef is one member: Type is an elementary Logix name ("DINT", "REAL",
// "BOOL", ...), "STRING" for string-shaped templates, or another TypeDef
// name. ArrayLen > 0 marks a fixed array member.
type FieldDef struct {
	Name     string
	Type     string
	ArrayLen int
}

// TagBinding maps one controller tag to one nautilus tag.
type TagBinding struct {
	// Name is the nautilus tag (what ST declares under VAR_EXTERNAL and Go
	// reads from the tag store).
	Name string
	// Device is the controller tag path, e.g. "Motor1" or
	// "Program:MainProgram.Counts".
	Device string
	// Type is an elementary name, "STRING", or a TypeDef name.
	Type string
	// ArrayLen > 0 reads the whole array (elements 0..ArrayLen-1).
	ArrayLen int
	// Writable includes the tag in the output set: the runtime's writes to
	// the nautilus tag propagate back to the controller (on change).
	Writable bool
	// ScanClass names the poll group this tag belongs to (see WithScanClass).
	// Empty means the default class; NoPoll catalogs the tag without polling
	// it. WithTagClass options in the driver constructor override this, so
	// generated manifests stay regenerable and policy lives in main.go.
	ScanClass string
}

// typeIndex resolves manifest types by name.
func (m Manifest) typeIndex() map[string]TypeDef {
	idx := make(map[string]TypeDef, len(m.Types))
	for _, t := range m.Types {
		idx[t.Name] = t
	}
	return idx
}

// structDefs builds the ir.StructDef for every manifest type, resolving
// nested references. The defs mirror what the generated ST TYPE block lowers
// to: same field names, same order — so values the driver constructs bind
// cleanly to VAR_EXTERNAL declarations.
func (m Manifest) structDefs() (map[string]*ir.StructDef, error) {
	idx := m.typeIndex()
	defs := make(map[string]*ir.StructDef, len(m.Types))
	var build func(name string, stack []string) (*ir.StructDef, error)

	irType := func(f FieldDef, stack []string) (*ir.Type, error) {
		var elem *ir.Type
		switch f.Type {
		case "BOOL":
			elem = ir.BoolT
		case "REAL", "LREAL":
			elem = ir.RealT
		case "STRING":
			elem = ir.StringT
		case "SINT", "INT", "DINT", "LINT", "USINT", "UINT", "UDINT", "ULINT",
			"BYTE", "WORD", "DWORD", "LWORD", "STIME", "DATE", "TIME_OF_DAY", "DATE_AND_TIME":
			elem = ir.IntT
		default:
			sd, err := build(f.Type, stack)
			if err != nil {
				return nil, err
			}
			elem = &ir.Type{Kind: ir.TypeStruct, Struct: sd}
		}
		if f.ArrayLen > 0 {
			return &ir.Type{Kind: ir.TypeArray, Elem: elem, ArrLen: f.ArrayLen, ArrLoBound: 0}, nil
		}
		return elem, nil
	}

	build = func(name string, stack []string) (*ir.StructDef, error) {
		if d, ok := defs[name]; ok {
			return d, nil
		}
		for _, s := range stack {
			if s == name {
				return nil, fmt.Errorf("eip: type cycle through %q", name)
			}
		}
		td, ok := idx[name]
		if !ok {
			return nil, fmt.Errorf("eip: manifest references unknown type %q", name)
		}
		sd := &ir.StructDef{Name: td.Name, FieldIndex: map[string]int{}}
		for i, f := range td.Fields {
			ft, err := irType(f, append(stack, name))
			if err != nil {
				return nil, err
			}
			sd.Fields = append(sd.Fields, ir.StructField{Name: f.Name, Type: ft})
			sd.FieldIndex[f.Name] = i
		}
		defs[name] = sd
		return sd, nil
	}

	for _, t := range m.Types {
		if _, err := build(t.Name, nil); err != nil {
			return nil, err
		}
	}
	return defs, nil
}

// elementary maps a manifest elementary type name to its CIP code, treating
// unknown names as struct types.
func elementaryCode(name string) (uint16, bool) {
	if name == "STRING" {
		return 0, false
	}
	t, ok := logix.TypeByName(name)
	if !ok {
		return 0, false
	}
	return t.Code, true
}
